<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vinarealte</title>
    <link rel="stylesheet" href="/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="/css/owl.carousel.css"/>
    <link rel="stylesheet" href="/css/owl.theme.css"/>
    <link rel="stylesheet" href="/css/font-awesome.css"/>
    <link rel="stylesheet" href="/css/fonts.css"/>
    <link rel="stylesheet" href="/css/main.css"/>
    <link rel="stylesheet" href="/css/bootstrap-select.min.css">

    <script type="application/javascript" src="/js/jquery-2.2.3.min.js"></script>
    <script type="application/javascript" src="/js/bootstrap-3.3.6.min.js"></script>
    <script type="application/javascript" src="/js/bootstrap-select.min.js"></script>
    <script type="application/javascript" src="/js/sprintf.min.js"></script>


    <script src="/js/scripts.js" type="text/javascript"></script>
</head>
<body>
<div class="content"><?php echo $this->content; ?></div>
<footer id="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="box-footer-shadow"></div>
            </div>
        </div>
        <div class="row list-item-footer">
            <div class="col-md-6">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Nhà bán</h3>
                        <ul>
                            <li><a href="#">Bán nhà Tân Phú</a></li>
                            <li><a href="#">Dự án căn hộ Jamona City</a></li>
                            <li><a href="#">Căn hộ Hưng Phát</a></li>
                            <li><a href="#">Căn hộ The Gold View</a></li>
                            <li><a href="#">Căn hộ The Art</a></li>
                            <li><a href="#">Căn hộ Đạt Gia Residence</a></li>
                            <li><a href="#">Biệt thự Park Riverside</a></li>
                            <li><a href="#">Căn hộ An Gia Riverside</a></li>
                            <li><a href="#">Đất nền dự án Vạn Phúc</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <h3>Nhà cho thuê</h3>
                        <ul>
                            <li><a href="#">Bán nhà Tân Phú</a></li>
                            <li><a href="#">Dự án căn hộ Jamona City</a></li>
                            <li><a href="#">Căn hộ Hưng Phát</a></li>
                            <li><a href="#">Căn hộ The Gold View</a></li>
                            <li><a href="#">Căn hộ The Art</a></li>
                            <li><a href="#">Căn hộ Đạt Gia Residence</a></li>
                            <li><a href="#">Biệt thự Park Riverside</a></li>
                            <li><a href="#">Căn hộ An Gia Riverside</a></li>
                            <li><a href="#">Đất nền dự án Vạn Phúc</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-6 box-address">
                <h3>CÔNG TY TNHH VINA REALTOR</h3>
                <p>Địa chỉ: Tầng 4, Tòa nhà Bảo Minh, 217 Nam Kỳ Khởi Nghĩa, Phường 7, Quận 3, TP. HCM.</p>
                <p>Tel: (08) 3932 9777 - (08) 3932 9333 - Fax: (08) 3932 9222.</p>
                <p>mail: <a href="mailto:contact@vinarealtor.vn">contact@vinarealtor.vn</a> - Hotline: 090 474 0278 (Ms.
                    Lan).</p>
                <p class="social">KẾT NỐI VỚI VINA REATOR:
                    <a class="icon icon-social-2" href="#"></a>
                    <a class="icon icon-circle" href="#"></a>
                    <a class="icon icon-social" href="#"></a>
                </p>
                <p class="connect"><span>WEBSITE CÙNG HỆ THỐNG: </span> <a href="#" class="icon icon-unimedia"></a></p>
            </div>
        </div>
    </div>
</footer>
<section class="coppyright">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul>
                    <li><a href="#">Về chúng tôi</a></li>
                    <li><a href="#">Tuyển dụng</a></li>
                    <li><a href="#">Hợp tác đầu tư</a></li>
                    <li><a href="#">Chính sách bảo mật thông tin</a></li>
                    <li><a href="#">Quy định đăng tin</a></li>
                    <li><a href="#">Hướng dẫn đăng tin</a></li>
                    <li><a href="#">Bảng giá dịch vụ</a></li>
                </ul>
            </div>
            <div class="col-md-12 vina-realtor"><a href="#">Copyright © 2016 by Vina Realtor</a></div>
        </div>
    </div>
</section>
<?php echo $this->inlineScript() ?>
</body>
</html>
