<pre class="h1 highlight">create post</pre>
<?php $actionUrl = $this->url("backend/post-create"); ?>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <?php $pf = $this->postForm;
            /** @var \Zend\Form\Form $pf */
            $pf->prepare();
            echo $this->form()->openTag($pf); ?>
            <div id="step-1">
                <div class="content-tab-step">
                    <h1>Vị trí nhà</h1>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("house_number")->getLabel();
                                    echo $this->formElement($pf->get('house_number'));
                                    echo $this->formElementErrors($pf->get('house_number')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("street")->getLabel();
                                    echo $this->formElement($pf->get('street'));
                                    echo $this->formElementErrors($pf->get('street')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("zip_code")->getLabel();
                                    echo $this->formElement($pf->get('zip_code'));
                                    echo $this->formElementErrors($pf->get('zip_code')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("provinceid")->getLabel();
                                    //                                    echo $this->formSelect($pf->get("provinceid"));
                                    echo $this->formUniSelect($pf->get("provinceid"));
                                    ?>
                                </label>
                            </div>

                            <div class="form-group">
                                <?php /** @var Zend\Form\Element\Select $districtSelect */
                                $districtSelect = $pf->get("districtid"); ?>
                                <label><?php echo $pf->get("districtid")->getLabel();
                                    echo $this->formSelect($districtSelect); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <?php /** @var Zend\Form\Element\Select $wardtSelect */
                                $wardtSelect = $pf->get("wardid"); ?>
                                <label><?php echo $pf->get("wardid")->getLabel();
                                    echo $this->formSelect($wardtSelect); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <?php /** @var Zend\Form\Element\Select $wardtSelect */
                                $categorySelect = $pf->get("category_id"); ?>
                                <label><?php echo $pf->get("category_id")->getLabel();
                                    echo $this->formUniSelect($categorySelect); ?>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Thông tin liên hệ</h1>
            <hr>
            <div id="step-2">
                <div class="content-tab-step step-2">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("fullname")->getLabel();
                                    echo $this->formElement($pf->get('fullname'));
                                    echo $this->formElementErrors($pf->get('fullname')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("company")->getLabel();
                                    echo $this->formElement($pf->get('company'));
                                    echo $this->formElementErrors($pf->get('company')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("email")->getLabel();
                                    echo $this->formElement($pf->get('email'));
                                    echo $this->formElementErrors($pf->get('email')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("phone")->getLabel();
                                    echo $this->formElement($pf->get('phone'));
                                    echo $this->formElementErrors($pf->get('phone')); ?>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Thông tin nhà đất</h1>
            <div id="step-3">
                <div class="content-tab-step step-2 step-3">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("price")->getLabel();
                                    echo $this->formElement($pf->get('price'));
                                    echo $this->formElementErrors($pf->get('price')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("price_installment")->getLabel();
                                    echo $this->formElement($pf->get('price_installment'));
                                    echo $this->formElementErrors($pf->get('price_installment')); ?>
                                </label>
                            </div>
                            <h2>Thông tin chi tiết</h2>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng ngủ </label>
                                    <select class="form-control"
                                            name="bed_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng khách</label>
                                    <select class="form-control"
                                            name="living_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng ăn </label>
                                    <select class="form-control"
                                            name="dining_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng làm việc </label>
                                    <select class="form-control"
                                            name="office_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng thờ </label>
                                    <select class="form-control"
                                            name="worship_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng giải trí </label>
                                    <select class="form-control"
                                            name="entertainment_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Ban công </label>
                                    <select class="form-control"
                                            name="balcony">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Hướng nhà </label>
                                    <select class="form-control"
                                            name="direction">
                                        <option value="dong">Đông
                                        </option>
                                        <option value="tay">Tây</option>
                                        <option value="nam">Nam</option>
                                        <option value="bac">Bắc</option>

                                        <option value="dong-nam">Đông
                                            Nam
                                        </option>
                                        <option value="dong-bac">Đông
                                            Bắc
                                        </option>
                                        <option value="tay-nam">Tây Nam
                                        </option>
                                        <option value="tay-bac">Tây-Bắc
                                        </option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Số tầng </label>
                                    <select class="form-control"
                                            name="floors">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>năm xây dựng </label>
                                    <input type="date"
                                           class="form-control"
                                           name="build_year">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label><?php echo $pf->get("area_use")->getLabel();
                                        echo $this->formElement($pf->get('area_use'));
                                        echo $this->formElementErrors($pf->get('area_use')); ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="taxHistoryComponent">
                <div class="row">
                    <h2>Lịch sử thuế</h2>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Năm</label>
                                    <select class="form-control" id="yearSelect">
                                        <option selected disabled hidden style="display: none">
                                            -- Năm --
                                        <option value="2016">2016</option>
                                        <option value="2015">2015</option>
                                        <option value="2014">2014</option>
                                        <option value="2013">2013</option>
                                        <option value="2012">2012</option>
                                        </option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-8">
                                <?php if($this->digitValidMsg != ""){ ?>
                                    <div class="alert alert-danger">
                                        <?php echo $this->digitValidMsg; ?>
                                    </div>
                                <?php } ?>
                                <div class="row">
                                    <div class="col-md-12"><label>Số tiền đóng</label></div>
                                </div>
                                <div class="row" id="taxHistory">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Hình ảnh và video</h1>
            <hr>
            <div id="step-4">
                <div class="row">
                    <div class="col-md-12"><h2>Thông tin mô tả</h2></div>
                    <div class="col-md-12"><p>Bạn có thể tải lên một số lượng không giới hạn các bức ảnh cho
                            danh sách nhà của bạn. Chọn các tập tin hình ảnh mà bạn muốn bằng cách nhấp vào
                            nút bên dưới. Nếu bạn thích, bạn cũng có thể kéo các bức ảnh của bạn vào vùng
                            thả dưới đây.</p></div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <div id="uploadImage">
                                <div id="dragDiv">
                                    <div class="uploads">
                                        <p>Kéo & Thả vào đây để tải ảnh<br>
                                            hoặc Chọn file</p>
                                    </div>
                                    <input type="file" id="inputFiles" name="uploadImage[]"
                                           multiple="multiple">
                                </div>
                                <div id="previewImageDiv"></div>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-12"><h2>Video clip</h2></div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Embedded Video</label>
                            <div style="position: relative">
                                <input id="youtubeUrl" type="text" name="youtubeUrl" value=""
                                       placeholder="Dán link youtube vào đây" class="form-control">
                                <div id="effect" class="btn btn-primary"
                                     style="display: none; position: absolute; right: 0; bottom: 0">nhấn
                                    enter
                                </div>
                            </div>
                            <div id="embedCode"></div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Mô tả</h1>
            <hr>
            <div id="step-5">
                <div class="content-tab-step step-2 step-3 step-4 step-5">
                    <div class="row">
                        <h2>Thông tin mô tả</h2>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("name")->getLabel();
                                    echo $this->formElement($pf->get("name"));
                                    echo $this->formElementErrors($pf->get("name")); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("excerpt")->getLabel();
                                    echo $this->formElement($pf->get("excerpt"));
                                    echo $this->formElementErrors($pf->get("excerpt")); ?>
                                </label>
                                <?php echo $this->formElementErrors($pf->get("excerpt")); ?>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("content")->getLabel();
                                    echo $this->formElement($pf->get("content"));
                                    echo $this->formElementErrors($pf->get("content")); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("website")->getLabel();
                                    echo $this->formElement($pf->get("website"));
                                    echo $this->formElementErrors($pf->get("website")); ?>
                                </label>
                            </div>
                        </div>
                        <h2>UNIT FEATURES</h2>
                        <div class="col-md-12">
                            <?php echo $this->formDeepCheckbox($pf->get("deepFeature")); ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->formElement($pf->get("submit")); ?>
            <?php //echo $this->formHidden($pf->get("loginCsrf"));
            $this->form()->closeTag($pf); ?>
        </div>
    </div>
</div>
<script src='<?php echo $this->basePath() . "/js/step.js"; ?>'></script>
<script>
    (function($){
        $(".parentDiv").each(function(){
            var parentDiv = $(this);
            var parentItem = parentDiv.find('input[type="checkbox"]').first();
            var childrenDiv = parentDiv.find(".childrenDiv");
            var numberOfChild = childrenDiv.find(
                'input[type="checkbox"]').length;

            if(numberOfChild > 0){
                console.log(parentItem);
                parentItem.attr("disabled", true);
            }
        });
        var stepItemsId = {
            item: {
                itemSelectPicker: {
                    proviceSelect: "provinceSelect",
                    districtSelect: "districtSelect",
                    wardSelect: "wardSelect"
                }
            }
        };
        var step = new Step("place", "step-1", stepItemsId);
        step.init();
        step.bindEventHanlder = function(){
            //render province
            var provinceSelectPicker = step.getItem(
                stepItemsId.item.itemSelectPicker.proviceSelect);
            var districtSelectPicker = step.getItem(
                stepItemsId.item.itemSelectPicker.districtSelect);
            var wardSelectPicker = step.getItem(
                stepItemsId.item.itemSelectPicker.wardSelect);

            provinceSelectPicker.on("change", function(){
                var provinceid = provinceSelectPicker.getSelectedOption().val();
                var oReq = step.ajaxCall("/post-tab/district",
                    {provinceid: provinceid});
                oReq.onload = function(){
                    var districtsOption = JSON.parse(
                        oReq.response)["districts"];
//                        console.log(districtsOption);
                    districtSelectPicker.render(districtsOption);

                };

            });

            districtSelectPicker.on("change", function(){
                var districtid = districtSelectPicker.getSelectedOption().val();
                var oReq = step.ajaxCall("/post-tab/ward",
                    {districtid: districtid});
                oReq.onload = function(){
                    var wardOption = JSON.parse(oReq.response)["wards"];
//                        console.log(wardOption);
                    wardSelectPicker.render(wardOption);
                };
            });
        };
        step.bindEventHanlder();

        var taxComponentItemIds = {
            item: {
                item: {
                    taxHistory: "taxHistory",
                    buildYear: "buildYear"
                },
                itemSelectPicker: {
                    yearSelect: "yearSelect"
                }
            }
        };
        var taxComponent = new Step("step3", "taxHistoryComponent", taxComponentItemIds);
        taxComponent.init();
        /**
         * HANDLE UNCOMMON ITEM
         */
        /**
         * handle getData for taxHistory
         * how to get out value from input/span,...
         * bcs taxHistory is a CUSTOM
         * not all step have it
         */
        var taxHistory = taxComponent.getItem(taxComponentItemIds.item.item.taxHistory);
        /**
         * custom item "tax history"
         * dynamic implements it here
         * we can do in step, but bcs not frequently used
         * >>> write it here
         * 2 most important NEED implement
         * getData
         * setData
         */
        taxHistory.getData = function(){
            var r = {};
            var records = [];
            taxHistory.find(".taxRecord").each(function(){
                var record = [];
                var houseTax = $(this).find("#houseTax").val();
                var year = $(this).find("#yearSelected").html();
                record.push(year, houseTax);
                records.push(record);
            });
            r[taxHistory.name] = records;
            return r;
        };
        taxHistory.setData = function(){
            /**
             * handle this function when we need
             * set back to review/edit
             */
        };
        /**
         * handle "buildYear"
         * get year, then conver to miliseconds
         * from Unix launched date
         */
        var buildYearItem = taxComponent.getItem(taxComponentItemIds.item.item.buildYear);
        buildYearItem.getData = function(){
            //convert date >>> int
            var r = {};
            var buildYear = new Date(buildYearItem.val());
            r[buildYearItem.name] = buildYear.getTime();
            return r;
        };
        buildYearItem.setData = function(milliseconds){
            //convert int >>> date
            var buildYear = new Date(milliseconds);
            buildYearItem.val(buildYear.toISOString().substring(0, 10))
        };
        taxComponent.bindEventHanlder = function(){
            var yearSelectPicker = taxComponent.getItem(taxComponentItemIds.item.itemSelectPicker.yearSelect);
            /**
             * when a year selected
             * taxHistory will append more row
             * for user input data
             */
            var taxHistory = taxComponent.getItem(taxComponentItemIds.item.item.taxHistory);
            var taxRecordSample = $(
                '<div class="row"> <div class="col-md-9"> <input type="number" placeholder="Số tiền"> </div> <div class="col-md-3"> <input type="text" class="yearSelected" readonly> </div> </div>');
            var yearSelectedSet = [];
            yearSelectPicker.on("change", function(){
                var yearSelected = yearSelectPicker.getSelectedOption().val();
                var picked = false;
                /**
                 * if user has clicked on a year
                 * we have created a record sample for him
                 * prevent him from create more
                 */
                for(var i in yearSelectedSet){
                    if(yearSelectedSet.hasOwnProperty(i)){
                        if(yearSelected == yearSelectedSet[i]){
                            picked = true;
                            break;
                        }
                    }
                }

                if(!picked){
                    var taxRecord = taxRecordSample.clone();
                    /**
                     * @warn hard code
                     * when find $("#<name>") like below
                     */
                    var name = "taxHistory[" + yearSelected + "][]";
                    taxRecord.find("input").each(function(){
                        $(this).attr("name", name);
                    });
                    taxRecord.find(".yearSelected").val(yearSelected);
                    taxHistory.append(taxRecord);
                }
                yearSelectedSet.push(yearSelected);

            });
        };
        taxComponent.bindEventHanlder();

        var step4ItemsId = {
            item: {
                item: {
                    uploadImage: "uploadImage",
                    embedCode: "embedCode"
                },
                itemInput: {
                    youtubeUrl: "youtubeUrl"
                }
            }
        };
        var step4 = new Step("step4", "step-4", step4ItemsId);
        step4.init();
        /**
         * handle custom item "dragDiv"
         */
        var uploadImage = step4.getItem(step4ItemsId.item.item.uploadImage);
        /**
         * bind event for dragDiv
         */
        var uploadImageNestedItemsId = {
            dragDiv: "dragDiv",
            inputFile: "inputFile",
            previewImageDiv: "previewImageDiv"
        };
        uploadImage.files = [];
        uploadImage.render = function(nestedItemsId){
            var preview = function(files, previewImageDiv){
                for(var i in files){
                    if(files.hasOwnProperty(i)){
                        var file = files[i];
                        var reader = new FileReader();
                        reader.onload = function(e){
                            //get image source
                            var imageSource = e.target.result;
                            //create new  image uploaded
                            var image = $("<img>");
                            //add src, id to image uploaded
                            //image has real size >>> on "load" get size WORK
                            image.css({
                                'max-width': '100%',
                                height: 100
                            });
                            image.attr("src", imageSource);
                            previewImageDiv.append(image);
                        };
                        reader.readAsDataURL(file);
                    }
                }
            };
            var dragDiv = uploadImage.find("#" + nestedItemsId.dragDiv);
            var inputFile = uploadImage.find("#" + nestedItemsId.inputFile);
            var previewImageDiv = uploadImage.find("#" + nestedItemsId.previewImageDiv);
            dragDiv.on("dragover", function(e){
                e.stopPropagation();
                e.preventDefault();
            });
            dragDiv.on("drop", function(e){
                e.stopPropagation();
                e.preventDefault();
                var originalEvent = e.originalEvent;
//                    console.log(e);
                // fetch FileList object
                var files = originalEvent.target.files || originalEvent.dataTransfer.files;
                uploadImage.files.push.apply(uploadImage.files, files);
//                    console.log(uploadImage.files);
                console.log(uploadImage.getData());
                preview(files, previewImageDiv);
            });
            inputFile.on("change", function(){
                var files = inputFile.get(0).files;
                uploadImage.files.push.apply(uploadImage.files, files);
//                    console.log(uploadImage.files);
                console.log(uploadImage.getData());
                preview(files, previewImageDiv);
            });
        };
//            uploadImage.render(uploadImageNestedItemsId);
        uploadImage.getData = function(){
            var r = {};
            r[this.name] = this.files;
            return r;
        };
        /**
         * handle "uploadImage" setData
         * for user preview their posted POST
         */
        uploadImage.setData = function(){
        };
        /**
         * handle "embedCode"
         */
        var embedCode = step4.getItem(step4ItemsId.item.item.embedCode);
        embedCode.render = function(url){
            var getId = function(url){
                var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
                var match = url.match(regExp);

                if(match && match[2].length == 11){
                    return match[2];
                }else{
                    return 'error';
                }
            };
            console.log(url);
            var videoId = getId(url);
            embedCode.videoId = videoId;
            console.log(videoId);
            var frame = $("<iframe>");
            var src = "https://www.youtube.com/embed/" + videoId;
            frame.attr("src", src);
            frame.attr("allowfullscreen", true);
            /**
             * only allow 1 video
             * empty embedCode first
             */
            embedCode.empty();
            embedCode.append(frame);
        };
        embedCode.getData = function(){
            var r = {};
            r[this.name] = embedCode.videoId;
            return r;
        };
        var youtubeUrl = step4.getItem(step4ItemsId.item.itemInput.youtubeUrl);
//            console.log(youtubeUrl);
        youtubeUrl.on("focus", function(){
//            $("#effect").fadeIn("fast");
        });
        youtubeUrl.on("change", function(){
            console.log("youtubeUrl on change");
            //funny effect hard code
            embedCode.render(youtubeUrl.val());
//            $("#effect").fadeOut("fast");
        });
        step4.render = function(){
            //after dynamic add feature to CUSTOM items
            //render them all in here
            uploadImage.render(uploadImageNestedItemsId);
        };
        step4.render();
        $("form").on("keypress", function(e){
            if(e.keyCode == 13){
                e.preventDefault();
            }
        }).on("submit", function(e){
//            e.preventDefault();

//            var uploadForm = new FormData();
            var uploadImages = step4.getItem(step4ItemsId.item.item.uploadImage).getData()["uploadImage"];
            var files = $("#inputFiles")[0].files;
            var lastI = Object.keys(files)[Object.keys(files).length - 1];
//            console.log("lastI", lastI);
//            console.log($("#inputFiles"));
//            console.log($("#inputFiles")[0].files[0]);
            for(var i in uploadImages){
                if(uploadImages.hasOwnProperty(i)){
                    files[parseInt(lastI, 10) + 1 + parseInt(i, 10)] = uploadImages[i];
                }
            }
//            console.log(uploadImages);
//            $("#inputFiles")[0].files[1] = uploadImages[0];
//            console.log($("#inputFiles")[0].files);
            console.log("files-manipulated", files);
//            $("#uploadImage").
            return true;
//            return false;
        });
    })(jQuery);
    $(document).ready(function(){


//        $("form").on("submit", function(e){
//            e.preventDefault();
////            console.log($(this).serializeArray());
//            var oReq = new XMLHttpRequest();
//            oReq.open("post", "/backend/post/create");
////            oReq.send(JSON.stringify($(this).serializeArray()));
////            oReq.send($(this).serialize());
//            var a = {name: "anh"};
//            oReq.send(JSON.stringify(a));
//            oReq.onload = function(){
//                console.log(oReq.response);
//            };
//
//        });
//        $("form").submit(function(e) {
//            var data = $(this).serialize();
//
//            var url = "/backend/post/create"; // the script where you handle the form input.
//
//            $.ajax({
//                type: "POST",
//                url: url,
//                data: $("form").serialize(), // serializes the form's elements.
//                success: function(response)
//                {
//                    console.log(response); // show response from the php script.
//                    //base on post_id, save img/tax history
//                }
//            });
//
//            e.preventDefault(); // avoid to execute the actual submit of the form.
//        });
    });
</script>
