<pre class="h1 highlight">create post</pre>
<?php $actionUrl = $this->url("backend/post-create"); ?>
<div class="container">
    <div class="row">
        <div class="col-md-9">
            <?php $pf = $this->postForm;
            /** @var \Zend\Form\Form $pf */
            $pf->prepare();
            echo $this->form()->openTag($pf); ?>
            <div id="step-1">
                <div class="content-tab-step">
                    <h1>Vị trí nhà</h1>
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("house_number")
                                        ->getLabel();
                                    echo $this->formElement($pf->get('house_number'));
                                    echo $this->formElementErrors($pf->get('house_number')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("street")
                                        ->getLabel();
                                    echo $this->formElement($pf->get('street'));
                                    echo $this->formElementErrors($pf->get('street')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("zip_code")
                                        ->getLabel();
                                    echo $this->formElement($pf->get('zip_code'));
                                    echo $this->formElementErrors($pf->get('zip_code')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("provinceid")
                                        ->getLabel();
                                    echo $this->formSelect($pf->get("provinceid")); ?>
                                </label>
                            </div>

                            <div class="form-group">
                                <?php /** @var Zend\Form\Element\Select $districtSelect */
                                $districtSelect = $pf->get("districtid"); ?>
                                <label><?php echo $pf->get("districtid")
                                        ->getLabel();
                                    echo $this->formSelect($districtSelect); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <?php /** @var Zend\Form\Element\Select $wardtSelect */
                                $wardtSelect = $pf->get("wardid"); ?>
                                <label><?php echo $pf->get("wardid")
                                        ->getLabel();
                                    echo $this->formSelect($wardtSelect); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <?php //echo $this->formDeepCheckbox($pf->get("deepCategory")); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Thông tin liên hệ</h1>
            <hr>
            <div id="step-2">
                <div class="content-tab-step step-2">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("fullname")
                                        ->getLabel();
                                    echo $this->formElement($pf->get('fullname'));
                                    echo $this->formElementErrors($pf->get('fullname')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("company")
                                        ->getLabel();
                                    echo $this->formElement($pf->get('company'));
                                    echo $this->formElementErrors($pf->get('company')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("email")->getLabel();
                                    echo $this->formElement($pf->get('email'));
                                    echo $this->formElementErrors($pf->get('email')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("phone")->getLabel();
                                    echo $this->formElement($pf->get('phone'));
                                    echo $this->formElementErrors($pf->get('phone')); ?>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Thông tin nhà đất</h1>
            <div id="step-3">
                <div class="content-tab-step step-2 step-3">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("price")->getLabel();
                                    echo $this->formElement($pf->get('price'));
                                    echo $this->formElementErrors($pf->get('price')); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("price_installment")
                                        ->getLabel();
                                    echo $this->formElement($pf->get('price_installment'));
                                    echo $this->formElementErrors($pf->get('price_installment')); ?>
                                </label>
                            </div>
                            <h2>Lịch sử thuế</h2>
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label>Năm</label>
                                        <select
                                            class="selectpicker form-control"
                                            data-live-search="true">
                                            <option data-tokens="1">2016
                                            </option>
                                            <option data-tokens="2">2015
                                            </option>
                                            <option data-tokens="3">2014
                                            </option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <h2>Thông tin chi tiết</h2>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng ngủ </label>
                                    <select class="form-control"
                                            name="bed_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng khách</label>
                                    <select class="form-control"
                                            name="living_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng ăn </label>
                                    <select class="form-control"
                                            name="dining_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng làm việc </label>
                                    <select class="form-control"
                                            name="office_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng thờ </label>
                                    <select class="form-control"
                                            name="worship_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Phòng giải trí </label>
                                    <select class="form-control"
                                            name="entertainment_rooms">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Ban công </label>
                                    <select class="form-control"
                                            name="balcony">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Hướng nhà </label>
                                    <select class="form-control"
                                            name="direction">
                                        <option value="dong">Đông
                                        </option>
                                        <option value="tay">Tây</option>
                                        <option value="nam">Nam</option>
                                        <option value="bac">Bắc</option>

                                        <option value="dong-nam">Đông
                                            Nam
                                        </option>
                                        <option value="dong-bac">Đông
                                            Bắc
                                        </option>
                                        <option value="tay-nam">Tây Nam
                                        </option>
                                        <option value="tay-bac">Tây-Bắc
                                        </option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>Số tầng </label>
                                    <select class="form-control"
                                            name="floors">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label>năm xây dựng </label>
                                    <input type="date"
                                           class="form-control"
                                           name="build_year">
                                </div>
                            </div>

                            <div class="col-md-4">
                                <div class="form-group">
                                    <label><?php echo $pf->get("area_use")
                                            ->getLabel();
                                        echo $this->formElement($pf->get('area_use'));
                                        echo $this->formElementErrors($pf->get('area_use')); ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Hình ảnh và video</h1>
            <hr>
            <div id="step-4">
                <div class="content-tab-step step-2 step-3 step-4">
                    <div class="row">
                        <div class="col-md-12"><h2>Thông tin mô tả</h2>
                        </div>
                        <div class="col-md-12"><p>Bạn có thể tải lên một số
                                lượng không giới hạn các bức ảnh cho
                                danh sách nhà của bạn. Chọn các tập tin hình
                                ảnh
                                mà bạn muốn bằng cách nhấp vào
                                nút bên dưới. Nếu bạn thích, bạn cũng có thể
                                kéo
                                các bức ảnh của bạn vào vùng
                                thả dưới đây.</p></div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="uploads">
                                    <p>Kéo & Thả vào đây để tải ảnh<br>
                                        hoặc Chọn file</p>
                                </div>
                            </div>

                        </div>
                        <div class="col-md-12"><h2>Video clip</h2></div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Embedded Video</label>
										<textarea class="form-control" rows="4"
                                                  placeholder="<iframe></iframe>"></textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <h1>Mô tả</h1>
            <hr>
            <div id="step-5">
                <div class="content-tab-step step-2 step-3 step-4 step-5">
                    <div class="row">
                        <h2>Thông tin mô tả</h2>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label><?php echo $pf->get("name")->getLabel();
                                    echo $this->formElement($pf->get("name"));
                                    echo $this->formElementErrors($pf->get("name")); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("excerpt")
                                        ->getLabel();
                                    echo $this->formElement($pf->get("excerpt"));
                                    echo $this->formElementErrors($pf->get("excerpt")); ?>
                                </label>
                                <?php echo $this->formElementErrors($pf->get("excerpt")); ?>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("content")
                                        ->getLabel();
                                    echo $this->formElement($pf->get("content"));
                                    echo $this->formElementErrors($pf->get("content")); ?>
                                </label>
                            </div>
                            <div class="form-group">
                                <label><?php echo $pf->get("website")
                                        ->getLabel();
                                    echo $this->formElement($pf->get("website"));
                                    echo $this->formElementErrors($pf->get("website")); ?>
                                </label>
                            </div>
                        </div>
                        <h2>UNIT FEATURES</h2>
                        <div class="col-md-12">
                            <?php echo $this->formDeepCheckbox($pf->get("deepFeature")); ?>
                        </div>
                    </div>
                </div>
            </div>
            <?php echo $this->formElement($pf->get("submit")); ?>
            <?php //echo $this->formHidden($pf->get("loginCsrf"));
            $this->form()->closeTag($pf); ?>
        </div>
    </div>
</div>
<script src='<?php echo $this->basePath() . "/js/step.js"; ?>'></script>
<script>
    (function($){
        $(".parentDiv").each(function(){
            var parentDiv = $(this);
            var parentItem = parentDiv.find('input[type="checkbox"]').first();
            var childrenDiv = parentDiv.find(".childrenDiv");
            var numberOfChild = childrenDiv.find(
                'input[type="checkbox"]').length;

            if(numberOfChild > 0){
                console.log(parentItem);
                parentItem.attr("disabled", true);
            }
        });
        var stepItemsId = {
            item: {
                itemSelectPicker: {
                    proviceSelect: "provinceSelect",
                    districtSelect: "districtSelect",
                    wardSelect: "wardSelect"
                }
            }
        };
        var step = new Step("place", "step-1", stepItemsId);
        step.init();
        step.bindEventHanlder = function(){
            //render province
            var provinceSelectPicker = step.getItem(
                stepItemsId.item.itemSelectPicker.proviceSelect);
            var districtSelectPicker = step.getItem(
                stepItemsId.item.itemSelectPicker.districtSelect);
            var wardSelectPicker = step.getItem(
                stepItemsId.item.itemSelectPicker.wardSelect);

            provinceSelectPicker.on("change", function(){
                var provinceid = provinceSelectPicker.getSelectedOption().val();
                var oReq = step.ajaxCall("/post-tab/district",
                    {provinceid: provinceid});
                oReq.onload = function(){
                    var districtsOption = JSON.parse(
                        oReq.response)["districts"];
//                        console.log(districtsOption);
                    districtSelectPicker.render(districtsOption);

                };

            });

            districtSelectPicker.on("change", function(){
                var districtid = districtSelectPicker.getSelectedOption().val();
                var oReq = step.ajaxCall("/post-tab/ward",
                    {districtid: districtid});
                oReq.onload = function(){
                    var wardOption = JSON.parse(oReq.response)["wards"];
//                        console.log(wardOption);
                    wardSelectPicker.render(wardOption);
                };
            });
        };
        step.bindEventHanlder();
    })(jQuery);
</script>
