<?php
namespace BackEnd\Controller;
use Zend\Mvc\Controller\AbstractActionController;

class TestController extends AbstractActionController{
    public function indexAction(){
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }
}