<section>
  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <h3>Danh sách Chuyên mục</h3>
        	<?php
			if(count($this->flash)){
				echo "<div class='alert alert-success'>";
				foreach($this->flash as $mess){
					echo $mess;
				}
				echo "</div>";
			}

		?>
        <table class="table table-striped">
          <tr>
            <td>STT</td>
            <td>Id</td>
            <td>Tên Chuyên Mục</td>
            <td>Category</td>
            <td>Status</td>
            <td>Memu-order</td>
            <td>Edit</td>
            <td>Delete</td>
          </tr>
          <?php
          if ($data) {
            foreach ($data as $key => $item) {
              ?>
              <tr>

                <td><?= $key + 1 ?></td>
                <td><?= $item['id'] ?></td>
                <td><?= $item['name'] ?></td>
                <td><?php
                  if ($item['parent'] == 0)
                    echo "gốc";
                  if ($item['parent'] != 0)
                    echo "+"
                    ?></td>
                <td><?php
                  if ($item['status'] == 1)
                    echo "Actived";
                  if ($item['status'] == 0)
                    echo "Actived";
                  ?>
                </td>
                <td>1</td>
                <td><a href = '<?= $this->url('backend/category', array('action' => 'edit', 'id' => $item['id'])) ?>'>Edit</td>
                <td><a href = '<?= $this->url('backend/category', array('action' => 'del', 'id' => $item['id'])) ?>'>Del</td>
              </tr>
              <?php
            }
          }
          ?>
        </table>
        <div class="col-md-12">
            <a class="a-btn-submit" href="<?php echo $this->url('backend/category', array('action' => 'add')); ?>">ADD NEW</a>
        </div>
      </div>
    </div>
  </div>
</section>