<header id="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="logo"><img src="images/vinarealor.png"></div>
                <div class="menu">
                    <div class="row">
                        <div class="col-lg-9">
                            <ul id="menu-top">
                                <li><a href="#">Cần mua</a></li>
                                <li><a href="#">Cần bán</a></li>
                                <li><a href="#">Cho thuê</a></li>
                                <li><a href="#">Nhà môi giới</a></li>
                                <li><a href="#">Tư vấn</a></li>
                                <li><a href="#">Thiết kế phòng</a></li>
                                <li><a href="#">Phong thủy</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <ul class="login">
                                <li><a href="#">Đăng ký</a></li>
                                <li><a href="#">Đăng nhập</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<section id="menu-user">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul id="menu-user-profile">
                    <li><a href="#">Quản lý</a></li>
                    <li><a href="#">Tài nguyên</a></li>
                    <li><a href="#">Đăng bài</a></li>
                    <li><a href="#">Hộp thư</a></li>
                    <li><a href="#">Cài đặt</a></li>
                    <li><a href="#">Trợ giúp</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section id="step1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <img src="images/banner-step.png">
                <div class="content-step">
                    <div class="content-step-1">
                        <h1>Đăng tin hoàn toàn miễn phí</h1>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-3">
                                        <input type="text" class="form-control" placeholder="Nhập số nhà">
                                    </div>
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" placeholder="Tên đường">
                                    </div>
                                    <div class="col-md-3">
                                        <input type="text" class="form-control zip" placeholder="Zip">
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-3">
                                        <select class="form-control">
                                            <option>-- Tỉnh/thành phố --</option>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <select class="form-control">
                                                    <option>-- Quận/huyện --</option>
                                                </select>
                                            </div>
                                            <div class="col-md-6">
                                                <select class="form-control">
                                                    <option>-- phường/xã --</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <input type="submit" value="Đi tiếp" class="btn btn-default">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
