<header id="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="logo"><img src="images/vinarealor.png"></div>
                <div class="menu">
                    <div class="row">
                        <div class="col-lg-9">
                            <ul id="menu-top">
                                <li><a href="#">Cần mua</a></li>
                                <li><a href="#">Cần bán</a></li>
                                <li><a href="#">Cho thuê</a></li>
                                <li><a href="#">Nhà môi giới</a></li>
                                <li><a href="#">Tư vấn</a></li>
                                <li><a href="#">Thiết kế phòng</a></li>
                                <li><a href="#">Phong thủy</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <ul class="login">
                                <li><a href="#">Đăng ký</a></li>
                                <li><a href="#">Đăng nhập</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<section id="menu-user">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul id="menu-user-profile">
                    <li><a href="#">Quản lý</a></li>
                    <li><a href="#">Tài nguyên</a></li>
                    <li><a href="#">Đăng bài</a></li>
                    <li><a href="#">Hộp thư</a></li>
                    <li><a href="#">Cài đặt</a></li>
                    <li><a href="#">Trợ giúp</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section id="step_tab">
    <div class="container">
        <div id="tabStep0">
            <div class="content-tab-step">
                <img src="images/banner-step.png">
                <div class="content-step">
                    <div class="content-step-1">
                        <h1>Đăng tin hoàn toàn miễn phí</h1>
                        <div class="row">
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-3">
                                        <input id="inputHouseNumber" type="text" class="form-control"
                                               placeholder="Nhập số nhà">
                                    </div>
                                    <div class="col-md-6">
                                        <input id="inputStreetName" type="text" class="form-control"
                                               placeholder="Tên đường">
                                    </div>
                                    <div class="col-md-3">
                                        <input id="inputZipCode" type="text" class="form-control zip" placeholder="Zip">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3" id="provincesDiv">
                                        <select id="provincesSelect" class="form-control selectpicker"></select>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div id="districtsDiv" class="col-md-6">
                                                <select id="districtsSelect" class="form-control">
                                                    <option selected disabled hidden style="display: none">-- Quận/Huyện
                                                        --
                                                    </option>
                                                </select>
                                            </div>
                                            <div id="wardsDiv" class="col-md-6">
                                                <select id="wardsSelect" class="form-control">
                                                    <option selected disabled hidden style="display: none">-- phường/xã
                                                        --
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <input type="submit" value="Đi tiếp" class="btn btn-default"
                                               id="btnSubmitStep0">
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" id="rowSteps" style="display: none">
            <div class="col-md-3">
                <ul class="nav nav-tabs tab-step-list" role="tablist">
                    <li role="presentation">
                        <a href="#step-1" aria-controls="step-1" role="tab" data-toggle="tab"
                           id="tabStep1"><span>1</span> Vị trí nhà</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-2" aria-controls="step-2" role="tab" data-toggle="tab"><span>2</span>Thông tin
                            liên hệ</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-3" aria-controls="step-3" role="tab" data-toggle="tab"><span>3</span>Thông tin
                            nhà đất</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-4" aria-controls="step-4" role="tab" data-toggle="tab"><span>4</span>Hình và
                            Video</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-5" aria-controls="step-5" role="tab" data-toggle="tab"><span>5</span>Mô tả</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-6" aria-controls="step-6" role="tab" data-toggle="tab"><span>6</span>Xem
                            trước</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane" id="step-1">
                        <div class="content-tab-step">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">nhập số nhà</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn tỉnh/thành phố</label>
                                        <select class="selectpicker form-control" data-live-search="true">
                                            <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
                                            <option data-tokens="mustard">Burger, Shake and a Smile</option>
                                            <option data-tokens="frosting">Sugar, Spice and all things nice</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Nhập tên đường</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn quận/huyện</label>
                                        <select class="selectpicker form-control" data-live-search="true">
                                            <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
                                            <option data-tokens="mustard">Burger, Shake and a Smile</option>
                                            <option data-tokens="frosting">Sugar, Spice and all things nice</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Mã zip/code</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn phường/xã</label>
                                        <select class="selectpicker form-control" data-live-search="true">
                                            <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
                                            <option data-tokens="mustard">Burger, Shake and a Smile</option>
                                            <option data-tokens="frosting">Sugar, Spice and all things nice</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn loại dư án</label>
                                        <select class="selectpicker form-control" data-live-search="true">
                                            <option data-tokens="ketchup mustard">Hot Dog, Fries and a Soda</option>
                                            <option data-tokens="mustard">Burger, Shake and a Smile</option>
                                            <option data-tokens="frosting">Sugar, Spice and all things nice</option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group step-category">
                                        <label for="number-address">Danh mục</label>
                                        <div class="list-radio">
                                            <ul>
                                                <li>
                                                    <input type="radio" id="shipadd2" name="address"/>
                                                    <label for="shipadd2">Nhà đất bán</label>
                                                </li>
                                                <li>
                                                    <input type="radio" id="shipadd" name="address"/>
                                                    <label for="shipadd">Nhà đất cho thuê</label>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next">Bước tiếp theo</button>
                                </div>
                                <div class="col-md-6"></div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-2">
                        <div class="content-tab-step step-2">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Họ và tên</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Tên công ty</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Email</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Số điện thoại</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group step-category">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next">Bước tiếp theo</button>
                                </div>
                                <div class="col-md-6"></div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-3">
                        <div class="content-tab-step step-2 step-3">
                            <div class="row">
                                <div class="col-md-12"><h2>Thông tin giá</h2></div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Giá bán</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Giá trả theo tháng</label>
                                        <input type="text" class="form-control" id="number-address">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                    </div>
                                </div>
                                <div class="col-md-12"><h2>Lịch sử thuế</h2></div>
                                <div class="col-md-12 tax">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Năm</label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">2016</option>
                                                    <option data-tokens="2">2015</option>
                                                    <option data-tokens="3">2014</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="row">
                                                <div class="col-md-12"><label>Số tiền đóng</label></div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="number-address">
                                                    </div>
                                                </div>
                                                <div class="col-md-3"><span class="tax-date">2016</span></div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="number-address">
                                                    </div>
                                                </div>
                                                <div class="col-md-3"><span class="tax-date">2015</span></div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="number-address">
                                                    </div>
                                                </div>
                                                <div class="col-md-3"><span class="tax-date">2014</span></div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="number-address">
                                                    </div>
                                                </div>
                                                <div class="col-md-3"><span class="tax-date">2013</span></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="number-address">
                                                    </div>
                                                </div>
                                                <div class="col-md-3"><span class="tax-date">2012</span></div>
                                            </div>

                                            <div class="row">
                                                <div class="col-md-9">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" id="number-address">
                                                    </div>
                                                </div>
                                                <div class="col-md-3"><span class="tax-date">2011</span></div>
                                            </div>

                                        </div>
                                    </div>
                                </div>


                                <div class="col-md-12"><h2>Thông tin chi tiết</h2></div>

                                <div class="col-md-12 step-3-detail">
                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Phòng ngủ </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Phòng khách</label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Phòng ăn </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Phòng làm việc </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Phòng thờ </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Phòng giải trí </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Ban công </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Hướng nhà </label>
                                                <select class="selectpicker form-control" data-live-search="true">
                                                    <option data-tokens="1">1</option>
                                                    <option data-tokens="2">2</option>
                                                    <option data-tokens="3">3</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Số tầng </label>
                                                <input type="number" class="form-control" id="number-address">
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">năm xây dựng </label>
                                                <input type="date" class="form-control" id="number-address">
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="number-address">Diện tích </label>
                                                <input type="number" class="form-control" id="number-address">
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next">Bước tiếp theo</button>
                                </div>

                                <div class="col-md-6"></div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-4">
                        <div class="content-tab-step step-2 step-3 step-4">
                            <div class="row">
                                <div class="col-md-12"><h2>Thông tin mô tả</h2></div>
                                <div class="col-md-12"><p>Bạn có thể tải lên một số lượng không giới hạn các bức ảnh cho
                                        danh sách nhà của bạn. Chọn các tập tin hình ảnh mà bạn muốn bằng cách nhấp vào
                                        nút bên dưới. Nếu bạn thích, bạn cũng có thể kéo các bức ảnh của bạn vào vùng
                                        thả dưới đây.</p></div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div class="uploads">
                                            <p>Kéo & Thả vào đây để tải ảnh<br>
                                                hoặc Chọn file</p>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-12"><h2>Video clip</h2></div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Embedded Video</label>
                                        <textarea class="form-control" rows="4"
                                                  placeholder="<iframe></iframe>"></textarea>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next">Bước tiếp theo</button>
                                </div>
                                <div class="col-md-6">

                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-5">
                        <div class="content-tab-step step-2 step-3 step-4 step-5">
                            <div class="row">
                                <div class="col-md-12"><h2>Thông tin mô tả</h2></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label for="number-address">Tiêu đề</label>
                                                <input type="text" class="form-control" id="number-address">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="number-address">Mô tả ngắn</label>
                                                <textarea class="form-control" rows="4"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="number-address">Nội dung</label>
                                                <textarea class="form-control" rows="4"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label for="number-address">Website</label>
                                                <input type="text" class="form-control" id="number-address">
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-md-12"><h2>UNIT FEATURES</h2></div>
                                <div class="col-md-12">
                                    <div class="unit-features">
                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Tính năng bổ sung</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Wet bar </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Jetted tub</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Skylights </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Sauna </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Jacuzzi / Whirlpool </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> High / Vaulted ceiling </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Hot tub / Spa </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Granite countertop </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Tile floor </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Hardwood floor </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Fireplace </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Máy móc gia dụng</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Trash compactor </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Freezer</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Stainless steel appliances </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Garbage disposal </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Microwave </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Dishwasher </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Refrigerator </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Range / Oven </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Nội thất bên ngoài</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Greenhouse </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Sprinkler system</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Garden </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Porch </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Pond </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Lake </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Lawn </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Fenced yard </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Yard </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Balcony, Deck, or Patio </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Private pool </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Sưởi & Làm lạnh</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Double pane / Storm windows </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Ceiling fans</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Air conditioning </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Central A/C </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Heat: forced air </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Sưởi & Làm lạnh</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Mother-in-law unit </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Office</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Pantry </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Breakfast nook </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Storage space </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Family room </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Master bath </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Walk-in closet </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Dining room </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Living room </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Solarium / Atrium </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Workshop </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Mud room </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Sun room </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Library </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Attic </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Recreation room </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Basement </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Wiring</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Intercom system </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Wired</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> High-speed internet </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Cable-ready </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12"><h2>COMMUNITY FEATURES</h2></div>

                                <div class="col-md-12">
                                    <div class="unit-features">
                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Building Type</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Assisted living</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Over 55 active community</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Loft layout </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Waterfront </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> New property </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Vintage building </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Communal Parking</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Garage - Detached </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> RV parking</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Garage - Attached </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> On-street parking </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Covered parking </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Off-street parking </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Guest parking </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Facilities & Recreation</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Dock </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Golf course</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Sports court </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Basketball court </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Tennis court </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Lake </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Business center </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Barbecue </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Pond </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Playground </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Clubhouse </label>
                                                    </div>

                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Near transportation </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Fitness center </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Shared pool </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-12"><h3><span>Security & Access</span></h3></div>
                                            <div class="col-md-12">
                                                <div class="row">
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Disability access </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Doorman</label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Security system </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Gated entry </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Controlled access </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Secured entry </label>
                                                    </div>
                                                    <div class="col-md-3">
                                                        <input type="checkbox" id="web-bar" value="">
                                                        <label for="web-bar"> Elevator </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next">Bước tiếp theo</button>
                                </div>
                                <div class="col-md-6">

                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-6">...</div>
                </div>
            </div>
        </div>
    </div>
</section>
<input type="hidden" id="provincesData" value='<?php echo json_encode($this->provinces); ?>'>
<script>
    (function($){
        $(document).ready(function(){
            $("#" + "btnSubmitStep0").on("click", function(){
                //hide step-0
                $("#" + "tabStep0").css({display: 'none'});
                //display tab-list, tab-content
                $("#" + "rowSteps").css({display: 'block'});
                $("a[aria-controls='step-1']").click();
            });
            /**
             * simple version of btn-next
             * @type {number}
             */
            var count = 0;
            $(".btn-next").on("click", function(){
                /**
                 * find out current selected
                 */
                count++;
                $("[aria-controls='step-" + count + "']").click();
            });
            var provincesData = JSON.parse($("#" + "provincesData").val());
            console.log(provincesData);
//            for(var key in provincesData){
//                if(provincesData.hasOwnProperty(key)){
//                    console.log(provincesData[key]["name"]);
//                }
//            }
            var provincesDiv = $("#" + "provincesDiv");
//            console.log(provincesDiv);
            var select = provincesDiv.find("#provincesSelect");
            select.attr("data-live-search", true);
            var blankOption = $('<option selected disabled hidden style="display: none">-- Tỉnh/thành phố --</option>');
            select.append(blankOption);
            console.log(select);
            for(var key in provincesData){
                if(provincesData.hasOwnProperty(key)){
                    var option = $("<option>");
                    option.val(provincesData[key]["provinceid"]);
//                    console.log(provincesData[key]["provinceid"]);
                    /**
                     * improve search by slug
                     * allow "ho chi minh" as "hồ chí minh"
                     */
//                    option.attr("data-tokens", "a");
                    option.html(provincesData[key]["name"]);
//                    console.log(provincesData[key]["name"]);
                    select.append(option);
                }
            }
            provincesDiv.append(select);

            select.on("change", function(){
                var selectedOption = $(this).find("option:selected");
                var provinceid = selectedOption.val();
                console.log(provinceid);
                /**
                 * ajax query to PostController
                 * get district based on provinceid
                 */
                var oReq = ajaxCall("/post-tab/district", provinceid);
                oReq.onload = function(){
                    console.log(oReq.response);
                    var districts = JSON.parse(oReq.response)["districts"];
                    console.log(districts);
                    /**
                     * build select picker for districts
                     */
                    var districtsDiv = $("#districtsDiv");
//                    districtsDiv.empty();

//                    var select = $("<select>");
                    var select = districtsDiv.find("#districtsSelect");
                    select.empty();
//                    select.addClass("form-control");
//                    select.addClass("selectpicker");

                    select.attr("data-live-search", true);
                    var blankOption = $(
                        ' <option selected disabled hidden style="display: none">-- Quận/Huyện --</option >');
                    select.append(blankOption);
                    for(var key in districts){
                        if(districts.hasOwnProperty(key)){
                            var district = districts[key];
                            console.log(district);
                            var option = $("<option>");
                            option.val(district["districtid"]);
                            var x = sprintf("%s %s", district["type"], district["name"]);
                            option.html(x);
                            select.append(option);
                        }
                    }
                    console.log(select);
                    districtsDiv.append(select);

                    select.on("change", function(){
                        var selectedOption = $(this).find("option:selected");
                        var districtid = selectedOption.val();
                        var oReq = ajaxCall("/post-tab/ward", districtid);
//                        console.log()
                        oReq.onload = function(){
                            console.log(oReq.response);
                            var wards = JSON.parse(oReq.response)["wards"];

                            var wardsDiv = $("#wardsDiv");
                            var select = wardsDiv.find("#wardsSelect");
                            select.empty();
                            var blankOption = $(
                                '<option selected disabled hidden style="display: none">-- phường/xã --</option>');
                            select.append(blankOption);
                            for(var key in wards){
                                if(wards.hasOwnProperty(key)){
                                    var ward = wards[key];
                                    console.log(ward);
                                    var option = $("<option>");
                                    option.val(ward["wardid"]);
                                    var x = sprintf("%s %s", ward["type"], ward["name"]);
                                    option.html(x);
                                    select.append(option);
                                }
                            }
                            wardsDiv.append(select);

                        }
                    });

                };
            });


        });

        function ajaxCall(url, provinceid){
            var formData = new FormData();
            formData.append("provinceid", provinceid);
            var oReq = new XMLHttpRequest();
            oReq.open("post", url);
            oReq.send(formData);
            return oReq;
        }
    })(jQuery);
</script>