<header id="header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="logo"><img src="images/vinarealor.png"></div>
                <div class="menu">
                    <div class="row">
                        <div class="col-lg-9">
                            <ul id="menu-top">
                                <li><a href="#">Cần mua</a></li>
                                <li><a href="#">Cần bán</a></li>
                                <li><a href="#">Cho thuê</a></li>
                                <li><a href="#">Nhà môi giới</a></li>
                                <li><a href="#">Tư vấn</a></li>
                                <li><a href="#">Thiết kế phòng</a></li>
                                <li><a href="#">Phong thủy</a></li>
                            </ul>
                        </div>
                        <div class="col-lg-3">
                            <ul class="login">
                                <li><a href="#">Đăng ký</a></li>
                                <li><a href="#">Đăng nhập</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<section id="menu-user">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <ul id="menu-user-profile">
                    <li><a href="#">Quản lý</a></li>
                    <li><a href="#">Tài nguyên</a></li>
                    <li><a href="#">Đăng bài</a></li>
                    <li><a href="#">Hộp thư</a></li>
                    <li><a href="#">Cài đặt</a></li>
                    <li><a href="#">Trợ giúp</a></li>
                </ul>
            </div>
        </div>
    </div>
</section>
<section id="step_tab">
    <div class="container">
        <div id="tabStep0">
            <div class="content-tab-step">
                <img src="images/banner-step.png">
                <div class="content-step">
                    <div class="content-step-0">
                        <h1>Đăng tin hoàn toàn miễn phí</h1>
                        <div class="row" id="step-0">
                            <div class="col-md-8">
                                <div class="row">
                                    <div class="col-md-3">
                                        <input id="houseNumber" type="text" class="form-control"
                                               placeholder="Nhập số nhà">
                                    </div>
                                    <div class="col-md-6">
                                        <input id="streetName" type="text" class="form-control"
                                               placeholder="Tên đường">
                                    </div>
                                    <div class="col-md-3">
                                        <input id="zipCode" type="text" class="form-control"
                                               placeholder="Zip">
                                    </div>
                                </div>

                                <div class="row">
                                    <div class="col-md-3">
                                        <select id="provincesSelect" class="form-control">
                                            <option selected disabled hidden style="display: none">
                                                -- Tỉnh/thành phố --
                                            </option>
                                        </select>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <select id="districtsSelect" class="form-control">
                                                    <option selected disabled hidden style="display: none">
                                                        -- Quận/Huyện--
                                                    </option>
                                                </select>
                                            </div>
                                            <div class="col-md-6">
                                                <select id="wardsSelect" class="form-control">
                                                    <option selected disabled hidden style="display: none">
                                                        -- phường/xã--
                                                    </option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <button id="btnSubmitStep0" class="btn btn-default">Đi tiếp</button>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-4"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row" id="rowSteps" style="display:none;">
            <div class="col-md-3">
                <ul class="nav nav-tabs tab-step-list" role="tablist">
                    <li role="presentation">
                        <a href="#step-1" aria-controls="step-1" role="tab" data-toggle="tab"
                           id="tabStep1"><span>1</span> Vị trí nhà</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-2" aria-controls="step-2" role="tab" data-toggle="tab"><span>2</span>Thông tin
                            liên hệ</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-3" aria-controls="step-3" role="tab" data-toggle="tab"><span>3</span>Thông tin
                            nhà đất</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-4" aria-controls="step-4" role="tab" data-toggle="tab"><span>4</span>Hình và
                            Video</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-5" aria-controls="step-5" role="tab" data-toggle="tab"><span>5</span>Mô tả</a>
                    </li>
                    <li role="presentation">
                        <a href="#step-6" aria-controls="step-6" role="tab" data-toggle="tab"><span>6</span>Xem
                            trước</a>
                    </li>
                </ul>
            </div>
            <div class="col-md-9">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane" id="step-1">
                        <div class="content-tab-step">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">nhập số nhà</label>
                                        <input id="houseNumber" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn tỉnh/thành phố</label>
                                        <select id="provincesSelect" class="form-control">
                                            <option selected disabled hidden style="display: none;">
                                                -- Tỉnh/thành phố--
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Nhập tên đường</label>
                                        <input id="streetName" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn quận/huyện</label>
                                        <select id="districtsSelect" class="form-control">
                                            <option selected disabled hidden style="display: none;">
                                                --Quận/Huyện--
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Mã zip/code</label>
                                        <input id="zipCode" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="number-address">Chọn phường/xã</label>
                                        <select id="wardsSelect" class="form-control">
                                            <option selected disabled hidden style="display: none;">
                                                --phường/xã--
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Chọn loại dư án</label>
                                        <select id="projectTypeSelect" class="form-control">
                                            <option selected disabled hidden style="display: none;">
                                                --Chọn loại dư án--
                                            </option>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Danh mục</label>
                                        <select id="categorySelect" class="form-control">
                                            <option selected disabled hidden style="display: none;">
                                                --Chọn danh mục--
                                            </option>
                                        </select>
                                        <!--                                            <ul>-->
                                        <!--                                                <li>-->
                                        <!--                                                    <input type="radio" name="address"/>-->
                                        <!--                                                    <label>Nhà đất bán</label>-->
                                        <!--                                                </li>-->
                                        <!--                                                <li>-->
                                        <!--                                                    <input type="radio" name="address"/>-->
                                        <!--                                                    <label>Nhà đất cho thuê</label>-->
                                        <!--                                                </li>-->
                                        <!--                                            </ul>-->
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <button id="btnSubmitStep1" type="submit" class="btn btn-primary btn-next">
                                    Bước tiếp theo
                                </button>
                            </div>
                            <div class="col-md-6"></div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-2">
                        <div class="content-tab-step step-2">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Họ và tên</label>
                                        <input id="fullName" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Tên công ty</label>
                                        <input id="companyName" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input id="email" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">

                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Số điện thoại</label>
                                        <input id="phone" type="text" class="form-control">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group step-category">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button id="btnSubmitStep2" type="submit" class="btn btn-primary btn-next">
                                        Bước tiếp theo
                                    </button>
                                </div>
                                <div class="col-md-6"></div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-3">
                        <div class="content-tab-step step-2 step-3">
                            <div class="row">
                                <div class="col-md-12"><h2>Thông tin giá</h2></div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Giá bán</label>
                                        <input type="text" class="form-control" id="housePrice">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Giá trả theo tháng</label>
                                        <input type="text" class="form-control" id="housePriceInstallment">
                                    </div>
                                </div>
                                <div class="col-md-12" id="thongtinchitiet">
                                    <h2>Thông tin chi tiết</h2>
                                    <div class="col-md-12 step-3-detail">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Phòng ngủ </label>
                                                    <select id="bedRooms" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Phòng khách</label>
                                                    <select id="livingRooms" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Phòng ăn </label>
                                                    <select id="diningRooms" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Phòng làm việc </label>
                                                    <select id="officeRooms" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Phòng thờ </label>
                                                    <select id="worshipRooms" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Phòng giải trí</label>
                                                    <select id="entertainmentRooms" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Ban công</label>
                                                    <select id="balcony" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Hướng nhà</label>
                                                    <select id="houseDirection" class="form-control">
                                                        <option value="dong">Đông</option>
                                                        <option value="tay">Tây</option>
                                                        <option value="nam">Nam</option>
                                                        <option value="bac">Bắc</option>

                                                        <option value="dong-nam">Đông Nam</option>
                                                        <option value="dong-bac">Đông Bắc</option>
                                                        <option value="tay-nam">Tây Nam</option>
                                                        <option value="tay-bac">Tây-Bắc</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Số tầng</label>
                                                    <select id="floors" class="form-control">
                                                        <option data-tokens="1">1</option>
                                                        <option data-tokens="2">2</option>
                                                        <option data-tokens="3">3</option>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>năm xây dựng</label>
                                                    <input id="buildYear" type="date" class="form-control">
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Diện tích</label>
                                                    <input type="text" id="houseArea" value=""
                                                           placeholder="Diện tích nhà - m2" class="form-control">
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-12" id="lichsuthue">
                                    <h2>Lịch sử thuế</h2>
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label>Năm</label>
                                                    <select class="form-control" id="yearSelect">
                                                        <option selected disabled hidden style="display: none">
                                                            -- Năm --
                                                        <option value="2016">2016</option>
                                                        <option value="2015">2015</option>
                                                        <option value="2014">2014</option>
                                                        <option value="2013">2013</option>
                                                        <option value="2012">2012</option>
                                                        </option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-8">
                                                <div class="row">
                                                    <div class="col-md-12"><label>Số tiền đóng</label></div>
                                                </div>
                                                <div class="row" id="taxHistory">
                                                    <!--                                                <div class="form-group">-->
                                                    <!--                                                    <div class="col-md-9" id="taxHistoryRecord">-->
                                                    <!--                                                        <div>-->
                                                    <!--                                                            <input type="text" value="" id="houseTax" placeholder="Số tiền" class="form-control">-->
                                                    <!--                                                        </div>-->
                                                    <!--                                                    </div>-->
                                                    <!--                                                    <div class="col-md-3">-->
                                                    <!--                                                        <span id="yearSelected" class="tax-date form-control">2016</span>-->
                                                    <!--                                                    </div>-->
                                                    <!--                                                </div>-->
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next" id="btnSubmitStep3">
                                        Bước tiếp theo
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-4">
                        <div class="content-tab-step step-2 step-3 step-4">
                            <div class="row">
                                <div class="col-md-12"><h2>Thông tin mô tả</h2></div>
                                <div class="col-md-12"><p>Bạn có thể tải lên một số lượng không giới hạn các bức ảnh cho
                                        danh sách nhà của bạn. Chọn các tập tin hình ảnh mà bạn muốn bằng cách nhấp vào
                                        nút bên dưới. Nếu bạn thích, bạn cũng có thể kéo các bức ảnh của bạn vào vùng
                                        thả dưới đây.</p></div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <div id="uploadImage">
                                            <div id="dragDiv">
                                                <div class="uploads">
                                                    <p>Kéo & Thả vào đây để tải ảnh<br>
                                                        hoặc Chọn file</p>
                                                </div>
                                                <input type="file" id="inputFile" name="imageFiles[]"
                                                       multiple="multiple">
                                            </div>
                                            <div id="previewImageDiv"></div>
                                        </div>
                                    </div>

                                </div>
                                <div class="col-md-12"><h2>Video clip</h2></div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Embedded Video</label>
                                        <div style="position: relative">
                                            <input id="youtubeUrl" type="text" name="youtubeUrl" value=""
                                                   placeholder="Dán link youtube vào đây" class="form-control">
                                            <div id="effect" class="btn btn-primary"
                                                 style="display: none; position: absolute; right: 0; bottom: 0">nhấn
                                                enter
                                            </div>
                                        </div>
                                        <div id="embedCode"></div>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <button id="btnSubmitStep4" type="submit" class="btn btn-primary btn-next">
                                        Bước tiếp theo
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-5">
                        <div class="content-tab-step step-2 step-3 step-4 step-5">
                            <div class="row">
                                <div class="col-md-12"><h2>Thông tin mô tả</h2></div>
                                <div class="col-md-12">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label for="number-address">Tiêu đề</label>
                                                <input type="text" class="form-control" id="postTitle">
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="number-address">Mô tả ngắn</label>
                                                <textarea class="form-control" rows="4" id=postExcerpt></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="number-address">Nội dung</label>
                                                <textarea class="form-control" rows="4" id="postContent"></textarea>
                                            </div>
                                        </div>
                                        <div class="col-md-8">
                                            <div class="form-group">
                                                <label for="number-address">Website</label>
                                                <input type="text" class="form-control" id="website">
                                            </div>
                                        </div>
                                    </div>

                                </div>

                                <div class="col-md-12"><h2>UNIT FEATURES</h2></div>
                                <div class="col-md-12">
                                    <div class="unit-features">
                                        <div class="row">
                                            <div class="panel-group" id="panelGroupFeature">
                                                <!--each panel is a child-->
<!--                                                <div class="panel panel-default">-->
<!--                                                    <div class="panel-heading">-->
<!--                                                        <h4 class="panel-title">-->
<!--                                                            <a data-toggle="collapse" data-parent="#panelGroupFeature" href="#1"-->
<!--                                                               id="houseFeatureTitle">-->
<!--                                                                Collapsible Group Item #1-->
<!--                                                            </a>-->
<!--                                                        </h4>-->
<!--                                                    </div>-->
<!--                                                    <div id="1" class="panel-collapse collapse in">-->
<!--                                                        <div class="panel-body" id="houseFeatureContent">-->
<!--                                                            div1-->
<!--                                                        </div>-->
<!--                                                    </div>-->
<!--                                                </div>-->
                                            </div>
                                        </div>
                                    </div>
                                </div>
<!--                                <div class="col-md-12"><h2>COMMUNITY FEATURES</h2></div>-->
                                <div class="col-md-12">
                                    <button type="submit" class="btn btn-primary btn-next" id="btnSubmitStep5">
                                        Bước tiếp theo
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div role="tabpanel" class="tab-pane" id="step-6">...</div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<input type="hidden" id="provincesData" value='<?php echo json_encode($this->provinces); ?>'>
<script>
    (function($){
        $(document).ready(function(){
            window.Step = function(name, divId, itemsId){
                this.component = $("#" + divId);
                this.items = [];
                this.itemsId = itemsId;
                this.data = {};
                this.data.name = name;
            };
            Step.prototype = {
                pushItem: function(item){
                    this.items[item.divId] = item;
                },
                getItem: function(divId){
                    return this.items[divId];
                },
                getData: function(){
                    var step = this;
                    for(var i in this.items){
                        if(this.items.hasOwnProperty(i)){
                            var item = this.items[i];
                            $.each(item.getData(), function(key, value){
                                step.data[key] = value;
                            });
                        }
                    }
                    return step.data;
                },
                init: function(){
                    var itemsId = this.itemsId["item"];
                    for(var itemType in itemsId){
                        if(itemsId.hasOwnProperty(itemType)){
                            for(var itemName in itemsId[itemType]){
                                if(itemsId[itemType].hasOwnProperty(itemName)){
                                    var itemDivId = itemsId[itemType][itemName];
                                    this[itemType](itemName, itemDivId);
                                }
                            }
                        }
                    }
                },
                item: function(name, divId){
                    var item = this.component.find("#" + divId);
                    item.name = name;
                    item.divId = divId;
                    this.pushItem(item);
                    return item;
                },
                itemInput: function(name, divId){
                    var input = this.item(name, divId);
                    input.getData = function(){
                        var r = {};
                        r[this.name] = input.val();
                        return r;
                    };
                    input.setData = function(d){
                        input.val(d);
                    };
                },
                itemTextArea: function(name, divId){
                    var textArea = this.item(name, divId);
                    textArea.getData = function(){
                        var r = {};
                        r[this.name] = textArea.html();
                        return r;
                    };
                    textArea.setData = function(d){
                        textArea.html(d);
                    };
                },
                itemSelectPicker: function(name, divId){
                    var selectPicker = this.item(name, divId);
                    selectPicker.render = function(options){
                        if(selectPicker.options){
                            //empty when created
                            selectPicker.empty();
                        }
                        selectPicker.options = options;
                        for(var key in options){
                            if(options.hasOwnProperty(key)){
                                var option = $("<option>");
                                option.val(options[key]["val"]);
                                option.html(options[key]["html"]);
                                selectPicker.append(option);
                            }
                        }
                    };
                    selectPicker.getData = function(){
                        var r = {};
                        r[this.name] = selectPicker.find("option:selected").val();
                        return r;
                    };
                    selectPicker.setSelectedOption = function(optionVal){
                        var option = this.find('option[value="' + optionVal + '"]');
                        option.attr("selected", true);
                    };
                    selectPicker.getSelectedOption = function(){
                        return selectPicker.find("option:selected");
                    }
                },
                /**
                 * CUSTOM ITEM
                 * input/selectpicker is most used
                 * itemRadio, itemCheckBox, itemDragDrop, not frequently
                 * beside of that "tax history" also has it own custom
                 * >>> add custom item dynamic in step
                 * >>> add it here
                 */
                itemRadio: function(name, divId){
                    var radioDiv = this.item(name, divId);
                    radioDiv.render = function(radios){
                        if(radioDiv.options){
                            //empty when created
                            radioDiv.empty();
                        }
                        radioDiv.options = radios;
                        for(var i in radios){
                            if(radios.hasOwnProperty(i)){
                                var radio = radios[i];
                                var div = $("<div>").addClass("radio-inline");
                                var input = $("<input>");
                                input.attr("name", name)
                                     .attr("type", "radio")
                                     .val(radio["input"]["val"]);
                                var label = $("<label>").html(radio["label"]["html"]);
                                div.append(input);
                                div.append(label);
                                radioDiv.append(div);
                            }
                        }
                    };
                    radioDiv.getData = function(){
                        var r = {};
                        var checkedRadio = radioDiv.find("input:checked");
//                        console.log(checkedRadio);
                        r[this.name] = checkedRadio.val();
                        return r;
                    }
                },
                itemCheckbox: function(name, divId){
                    var checkboxDiv = this.item(name, divId);
                    checkboxDiv.render = function(checkboxs){
                        if(checkboxDiv.options){
                            //empty when created
                            checkboxDiv.empty();
                        }
                        checkboxDiv.options = checkboxs;
                        for(var i in checkboxs){
                            if(checkboxs.hasOwnProperty(i)){
                                var checkbox = checkboxs[i];
                                var div = $("<div>");
                                var input = $("<input>");
//                                input.attr("name", "name");
                                input.attr("type", "checkbox")
                                     .val(checkbox["id"]);
//                                var label = $("<label>").html(radio["label"]["html"]);
                                var label = $("<label>").addClass("checkbox-inline");;
                                label.append(input);
                                label.append(checkbox["name"]);
//                                div.append(input);
                                div.append(label);
                                checkboxDiv.append(div);
                            }
                        }
                    };
                    checkboxDiv.getData = function(){
                        var r = {};
                        var checkedBoxs = [];
                        checkboxDiv.find("input:checked").each(function(){
                            checkedBoxs.push($(this).val());
                        });
//                        console.log(checkedRadio);
                        r[this.name] = checkedBoxs;
                        return r;
                    };
//                    return checkboxDiv;
                },
                ajaxCall: function(url, data){
                    var formData = new FormData();
                    for(var key in data){
                        if(data.hasOwnProperty(key)){
                            formData.append(key, data[key]);
                        }
                    }
                    var oReq = new XMLHttpRequest();
                    oReq.open("post", url);
                    oReq.send(formData);
                    return oReq;
                }
            };
            var step0ItemsId = {
                item: {
                    itemInput: {
                        house: "houseNumber",
                        street: "streetName",
                        zipCode: "zipCode"
                    },
                    itemSelectPicker: {
                        province: "provincesSelect",
                        district: "districtsSelect",
                        ward: "wardsSelect"
                    }
                },
                event: {
                    btnSubmit: "btnSubmitStep0"
                }
            };
            var step0 = new Step("step0", "step-0", step0ItemsId);
            step0.init();
            step0.render = function(){
                //render province
                var provinceSelectPicker = step0.getItem(step0ItemsId.item.itemSelectPicker.province);
                var districtSelectPicker = step0.getItem(step0ItemsId.item.itemSelectPicker.district);
                var wardSelectPicker = step0.getItem(step0ItemsId.item.itemSelectPicker.ward);

                var provincesOption = JSON.parse($("#provincesData").val());
//                console.log(provinceSelectPicker);
                provinceSelectPicker.addClass("selectpicker");
                provinceSelectPicker.attr("data-live-search", true);
                provinceSelectPicker.render(provincesOption);
                provinceSelectPicker.on("change", function(){
                    var provinceid = provinceSelectPicker.getSelectedOption().val();
                    var oReq = step0.ajaxCall("/post-tab/district", {provinceid: provinceid});
                    oReq.onload = function(){
                        var districtsOption = JSON.parse(oReq.response)["districts"];
//                        console.log(districtsOption);
                        districtSelectPicker.render(districtsOption);

                    };

                });

                districtSelectPicker.on("change", function(){
                    var districtid = districtSelectPicker.getSelectedOption().val();
                    var oReq = step0.ajaxCall("/post-tab/ward", {districtid: districtid});
                    oReq.onload = function(){
                        var wardOption = JSON.parse(oReq.response)["wards"];
//                        console.log(wardOption);
                        wardSelectPicker.render(wardOption);
                    };
                });
            };
            step0.render();
            step0.bindEventHanlder = function(){
                var btnSubmit = step0.component.find("#" + this.itemsId.event.btnSubmit);
                btnSubmit.on("click", function(){
                    console.log("step0Data", step0.getData());
                    $("#" + "tabStep0").css({display: 'none'});
                    //display tab-list, tab-content
                    $("#" + "rowSteps").css({display: 'block'});
                    $("a[aria-controls='step-1']").click();
                    //start render step1
                    step1.render();
                });


            };
            step0.bindEventHanlder();


            var step1ItemsId = {
                item: {
                    itemInput: {
                        house: "houseNumber",
                        street: "streetName",
                        zipCode: "zipCode"
                    },
                    itemSelectPicker: {
                        province: "provincesSelect",
                        district: "districtsSelect",
                        ward: "wardsSelect",
                        parentCategory: "projectTypeSelect",
                        category: "categorySelect"
                    }
//                    , itemRadio: {}
                },
                event: {
                    btnSubmit: "btnSubmitStep1"
                }

            };
            var step1 = new Step("step1", "step-1", step1ItemsId);
//            console.log(step1);
            step1.init();
            step1.render = function(){
                //get item input
                var inputHouseNumber = step1.getItem(step1ItemsId.item.itemInput.house);
                var inputStreetName = step1.getItem(step1ItemsId.item.itemInput.street);
                var inputZipCode = step1.getItem(step1ItemsId.item.itemInput.zipCode);
                //get item select picker
                var provinceSelectPicker = step1.getItem(step1ItemsId.item.itemSelectPicker.province);
                var districtSelectPicker = step1.getItem(step1ItemsId.item.itemSelectPicker.district);
                var wardSelectPicker = step1.getItem(step1ItemsId.item.itemSelectPicker.ward);
                //add listener
                provinceSelectPicker.on("change", function(){
                    var provinceid = provinceSelectPicker.getSelectedOption().val();
                    var oReq = step1.ajaxCall("/post-tab/district", {provinceid: provinceid});
                    oReq.onload = function(){
                        var districtsOption = JSON.parse(oReq.response)["districts"];
//                        console.log(districtsOption);
                        districtSelectPicker.render(districtsOption);
                    };

                });
                //add listener
                districtSelectPicker.on("change", function(){
                    var districtid = districtSelectPicker.getSelectedOption().val();
                    var oReq = step1.ajaxCall("/post-tab/ward", {districtid: districtid});
                    oReq.onload = function(){
                        var wardOption = JSON.parse(oReq.response)["wards"];
//                        console.log(wardOption);
                        wardSelectPicker.render(wardOption);
                    };
                });

                //based on step0, set item
                var step0Data = step0.getData();
//                provinceSelectPicker.addClass("selectpicker");
//                provinceSelectPicker.attr("data-live-search", true);
                provinceSelectPicker.render(step0.getItem(step0ItemsId.item.itemSelectPicker.province).options);
//                console.log(step0.getItem(step0ItemsId.item.itemSelectPicker.district).options);
                districtSelectPicker.render(step0.getItem(step0ItemsId.item.itemSelectPicker.district).options);
                wardSelectPicker.render(step0.getItem(step0ItemsId.item.itemSelectPicker.ward).options);
                //set item input based on step0Data
                inputHouseNumber.setData(step0Data["house"]);
                inputStreetName.setData(step0Data["street"]);
                inputZipCode.setData(step0Data["zipCode"]);
                //set item select picker based on step0Data
                provinceSelectPicker.setSelectedOption(step0Data["province"]);
//                console.log(step0Data["district"]);
                districtSelectPicker.setSelectedOption(step0Data["district"]);
                wardSelectPicker.setSelectedOption(step0Data["ward"]);

                var parentCategorySelectPicker = step1.getItem(step1ItemsId.item.itemSelectPicker.parentCategory);
                var oReq = step1.ajaxCall("/post-tab/parent-category", {parentCategory: "parentCategory"});
                oReq.onload = function(){
//                    console.log(oReq.response);
                    var parentCategoryOption = JSON.parse(oReq.response)["parentCategory"];
//                    console.log(parentCategoryOption);
                    parentCategorySelectPicker.render(parentCategoryOption);
                };

                var categorySelectPicker = step1.getItem(step1ItemsId.item.itemSelectPicker.category);
                parentCategorySelectPicker.on("change", function(){
                    var parentCategoryId = parentCategorySelectPicker.getSelectedOption().val();
//                    console.log("parentCategoryId", parentCategoryId);
                    var oReq = step1.ajaxCall("/post-tab/category", {parentCategoryId: parentCategoryId});
                    oReq.onload = function(){
//                        console.log(oReq.response);
                        var categoryOption = JSON.parse(oReq.response)["category"];
//                        console.log(categoryOption);
                        categorySelectPicker.render(categoryOption);
                    };

                });


//                var categoryRadioDiv = step1.getItem(step1ItemsId.item.itemRadio.category);
//                var oReq1 = step1.ajaxCall("/post-tab/category", {parentCate: "category"});
//                oReq1.onload = function(){
//                    var categoryRadio = JSON.parse(oReq1.response)["category"];
////                    console.log(categoryRadio);
//                    categoryRadioDiv.render(categoryRadio);
//                };

//                categoryRadioDiv.on("change", function(){
//                    var v = categoryRadioDiv.getData();
//                    console.log(v);
//                })
            };
            step1.bindEventHanlder = function(){
                var btnSubmit = step1.component.find("#" + step1.itemsId.event.btnSubmit);
                btnSubmit.on("click", function(){
                    console.log("step1Data", step1.getData());
                    $("a[aria-controls='step-2']").click();
//                    step2.render();
                });
            };
            step1.bindEventHanlder();

            var step2ItemsId = {
                item: {
                    itemInput: {
                        fullName: "fullName",
                        companyName: "companyName",
                        email: "email",
                        phone: "phone"
                    }
                },
                event: {
                    btnSubmit: "btnSubmitStep2"
                }
            };
            var step2 = new Step("step2", "step-2", step2ItemsId);
            step2.init();
//            step2.render = function(){
//
//            }
            step2.bindEventHanlder = function(){
                var btnSubmit = step2.component.find("#" + step2.itemsId.event.btnSubmit);
                btnSubmit.on("click", function(){
                    console.log("step2Data", step2.getData());
                    $("a[aria-controls='step-3']").click();
//                    step3.render();
                });
            };
            step2.bindEventHanlder();

            var step3ItemsId = {
                item: {
                    itemInput: {
                        housePrice: "housePrice",
                        housePriceInstallment: "housePriceInstallment",
                        houseArea: "houseArea",
                    },
                    itemSelectPicker: {
                        yearSelect: "yearSelect",
                        bedRooms: "bedRooms",
                        livingRooms: "livingRooms",
                        diningRooms: "diningRooms",
                        officeRooms: "officeRooms",
                        worshipRooms: "worshipRooms",
                        entertainmentRooms: "entertainmentRooms",
                        balcony: "balcony",
                        houseDirection: "houseDirection",
                        floors: "floors"
                    },
                    item: {
                        taxHistory: "taxHistory",
                        buildYear: "buildYear"
                    }
                },
                event: {
                    btnSubmit: "btnSubmitStep3"
                }
            };
            var step3 = new Step("step3", "step-3", step3ItemsId);
            step3.init();
            /**
             * HANDLE UNCOMMON ITEM
             */
            /**
             * handle getData for taxHistory
             * how to get out value from input/span,...
             * bcs taxHistory is a CUSTOM
             * not all step have it
             */
            var taxHistory = step3.getItem(step3ItemsId.item.item.taxHistory);
            /**
             * custom item "tax history"
             * dynamic implements it here
             * we can do in step, but bcs not frequently used
             * >>> write it here
             * 2 most important NEED implement
             * getData
             * setData
             */
            taxHistory.getData = function(){
//                return {taxHistory: "taxHistory"};
                var r = {};
                var records = [];
                var houseArea = step3.getItem(step3ItemsId.item.itemInput.houseArea).val();
//                console.log("houseArea", houseArea);
                taxHistory.find(".taxRecord").each(function(){
                    var record = [];
                    var houseTax = $(this).find("#houseTax").val();
//                    console.log("houseTax", houseTax);
                    var year = $(this).find("#yearSelected").html();
                    record.push(year, houseArea, houseTax);
                    records.push(record);
                });
                r[taxHistory.name] = records;
                return r;
            };
            taxHistory.setData = function(){
                /**
                 * handle this function when we need
                 * set back to review/edit
                 */
            };
            /**
             * handle "buildYear"
             * get year, then conver to miliseconds
             * from Unix launched date
             */
            var buildYearItem = step3.getItem(step3ItemsId.item.item.buildYear);
            buildYearItem.getData = function(){
                //convert date >>> int
                var r = {};
                var buildYear = new Date(buildYearItem.val());
                r[buildYearItem.name] = buildYear.getTime();
                return r;
            };
            buildYearItem.setData = function(milliseconds){
                //convert int >>> date
                var buildYear = new Date(milliseconds);
                buildYearItem.val(buildYear.toISOString().substring(0, 10))
            };
            step3.bindEventHanlder = function(){
                var yearSelectPicker = step3.getItem(step3ItemsId.item.itemSelectPicker.yearSelect);
                /**
                 * when a year selected
                 * taxHistory will append more row
                 * for user input data
                 */
                var taxHistory = step3.getItem(step3ItemsId.item.item.taxHistory);
                var taxRecordSample = $(
                    '<div class="form-group taxRecord"> <div class="col-md-9" id="taxHistoryRecord"> <div> <input type="text" value="" id="houseTax" placeholder="Số tiền" class="form-control"> </div> </div> <div class="col-md-3"> <span id="yearSelected" class="tax-date form-control">2016</span> </div> </div>');
                var yearSelectedSet = [];
                yearSelectPicker.on("change", function(){
                    var yearSelected = yearSelectPicker.getSelectedOption().val();
//                    console.log("yearSelected", yearSelected);
                    var picked = false;
                    /**
                     * if user has clicked on a year
                     * we have created a record sample for him
                     * prevent him from create more
                     */
                    for(var i in yearSelectedSet){
                        if(yearSelectedSet.hasOwnProperty(i)){
//                            console.log("check picked");
                            if(yearSelected == yearSelectedSet[i]){
                                picked = true;
                                break;
                            }
                        }
                    }
//                    console.log("picked status", picked);
                    if(!picked){
                        var taxRecord = taxRecordSample.clone();
                        /**
                         * @warn hard code
                         * when find $("#<name>") like below
                         */
                        taxRecord.find("#yearSelected").html(yearSelected);
                        taxHistory.append(taxRecord);
                    }
                    yearSelectedSet.push(yearSelected);

                });
                /**
                 * hanlde button click
                 * btnSubmitStep3
                 */
                var btnSubmit = step3.component.find("#" + step3.itemsId.event.btnSubmit);
                btnSubmit.on("click", function(){
                    console.log("step3Data", step3.getData());
                    $("a[aria-controls='step-4']").click();
//                    step3.render();
                });
            };
            step3.bindEventHanlder();

            var step4ItemsId = {
                item: {
                    item: {
                        uploadImage: "uploadImage",
                        embedCode: "embedCode"
                    },
                    itemInput: {
                        youtubeUrl: "youtubeUrl"
                    }
                },
                event: {
                    btnSubmit: "btnSubmitStep4"
                }
            };
            var step4 = new Step("step4", "step-4", step4ItemsId);
            step4.init();
            /**
             * handle custom item "dragDiv"
             */
            var uploadImage = step4.getItem(step4ItemsId.item.item.uploadImage);
            /**
             * bind event for dragDiv
             */
            var uploadImageNestedItemsId = {
                dragDiv: "dragDiv",
                inputFile: "inputFile",
                previewImageDiv: "previewImageDiv"
            };
            uploadImage.files = [];
            uploadImage.render = function(nestedItemsId){
                var preview = function(files, previewImageDiv){
                    for(var i in files){
                        if(files.hasOwnProperty(i)){
                            var file = files[i];
                            var reader = new FileReader();
                            reader.onload = function(e){
                                //get image source
                                var imageSource = e.target.result;
                                //create new  image uploaded
                                var image = $("<img>");
                                //add src, id to image uploaded
                                //image has real size >>> on "load" get size WORK
                                image.css({
                                    'max-width': '100%',
                                    height: 100
                                });
                                image.attr("src", imageSource);
                                previewImageDiv.append(image);
                            };
                            reader.readAsDataURL(file);
                        }
                    }
                };
                var dragDiv = uploadImage.find("#" + nestedItemsId.dragDiv);
                var inputFile = uploadImage.find("#" + nestedItemsId.inputFile);
                var previewImageDiv = uploadImage.find("#" + nestedItemsId.previewImageDiv);
                dragDiv.on("dragover", function(e){
                    e.stopPropagation();
                    e.preventDefault();
                });
                dragDiv.on("drop", function(e){
                    e.stopPropagation();
                    e.preventDefault();
                    var originalEvent = e.originalEvent;
//                    console.log(e);
                    // fetch FileList object
                    var files = originalEvent.target.files || originalEvent.dataTransfer.files;
                    uploadImage.files.push.apply(uploadImage.files, files);
//                    console.log(uploadImage.files);
                    console.log(uploadImage.getData());
                    preview(files, previewImageDiv);
                });
                inputFile.on("change", function(){
                    var files = inputFile.get(0).files;
                    uploadImage.files.push.apply(uploadImage.files, files);
//                    console.log(uploadImage.files);
                    console.log(uploadImage.getData());
                    preview(files, previewImageDiv);
                });
            };
//            uploadImage.render(uploadImageNestedItemsId);
            uploadImage.getData = function(){
                var r = {};
                r[this.name] = this.files;
                return r;
            };
            /**
             * handle "uploadImage" setData
             * for user preview their posted POST
             */
            uploadImage.setData = function(){
            };
            /**
             * handle "embedCode"
             */
            var embedCode = step4.getItem(step4ItemsId.item.item.embedCode);
            embedCode.render = function(url){
                var getId = function(url){
                    var regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/;
                    var match = url.match(regExp);

                    if(match && match[2].length == 11){
                        return match[2];
                    }else{
                        return 'error';
                    }
                };
                console.log(url);
                var videoId = getId(url);
                embedCode.videoId = videoId;
                console.log(videoId);
                var frame = $("<iframe>");
                var src = "https://www.youtube.com/embed/" + videoId;
                frame.attr("src", src);
                frame.attr("allowfullscreen", true);
                /**
                 * only allow 1 video
                 * empty embedCode first
                 */
                embedCode.empty();
                embedCode.append(frame);
            };
            embedCode.getData = function(){
                var r = {};
                r[this.name] = embedCode.videoId;
                return r;
            };
            var youtubeUrl = step4.getItem(step4ItemsId.item.itemInput.youtubeUrl);
//            console.log(youtubeUrl);
            youtubeUrl.on("focus", function(){
                $("#effect").fadeIn("fast");
            });
            youtubeUrl.on("change", function(){
                console.log("youtubeUrl on change");
                //funny effect hard code
                embedCode.render(youtubeUrl.val());
                $("#effect").fadeOut("fast");
            });
            step4.render = function(){
                //after dynamic add feature to CUSTOM items
                //render them all in here
                uploadImage.render(uploadImageNestedItemsId);
            };
            step4.render();
            step4.bindEventHanlder = function(){
                var btnSubmit = step4.component.find("#" + step4ItemsId.event.btnSubmit);
                btnSubmit.on("click", function(){
                    console.log("step4Data", step4.getData());
                    $("a[aria-controls='step-5']").click();
                    //call on step5
                });
            };
            step4.bindEventHanlder();

            var step5ItemsId = {
                item:{
                    item: {
                        panelGroupFeature: "panelGroupFeature"
                    },
                    itemInput: {
                        postTitle: "postTitle",
                        website: "website"
                    },
                    itemTextArea: {
                        postExcerpt: "postExcerpt",
                        postContent: "postContent"
                    }
                },
                event: {
                    btnSubmit: "btnSubmitStep5"
                }
            };
            var step5 = new Step("step5", "step-5", step5ItemsId);
            step5.init();
            /**
             * add item "itemTextArea"
             */
            /**
             * handle CUSTOM item "panelGroupFeature"
             */
            /**
             * 1. ajax call get data
             * [
             *  "group" : [],
             *  "group-2": [],
             *  "group-3": [],
             *  ]
             *  2. render "collapse panel"
             *  based on json data
             *  3. getData
             *  4. setData
             */
            var panelGroupFeature = step5.getItem(step5ItemsId.item.item.panelGroupFeature);
            panelGroupFeature.render = function(){
                /**
                 * ajax call get data
                 */
                var panelItemSample = $('<div class="panel panel-default"><div class="panel-heading"><h4 class="panel-title"><a data-toggle="collapse" data-parent="#panelGroupFeature" id="houseFeatureTitle"></a> </h4></div><div class="panel-collapse collapse"><div class="panel-body" id="houseFeatureContent"></div></div></div>');
                var oReq = step5.ajaxCall("/post-tab/features");
                oReq.onload = function(){
                    console.log(oReq.response);
                    var features = JSON.parse(oReq.response)["features"];
                    console.log(features);
                    /**
                     * this count allow <a> href to "panel-collapse"
                     * @type {number}
                     */
                    var count = 0;
                    var dumpStepItemsId = {item: {itemCheckbox:{}}};
                    for(var panelItemTitle in features){
                        if(features.hasOwnProperty(panelItemTitle)){
                            //create panelItem from sample
                            var panelItem = panelItemSample.clone();
                            //find "title", add title for group
                            panelItem.find("#houseFeatureTitle").html(panelItemTitle);
                            panelItem.find("#houseFeatureTitle").attr("href", "#" + count);
                            //href --> "panel-collapse"
                            panelItem.find(".panel-collapse").attr("id", count);
                            //handle "in" attr for first one
                            if(count == 0){
                                panelItem.find(".panel-collapse").addClass("in");
                            }
                            var checkboxDivId = "checkboxDiv_" + count;
                            dumpStepItemsId.item.itemCheckbox[panelItemTitle] = checkboxDivId;
                            var checkboxDiv = '<div id="' + checkboxDivId + '"></div>';
                            panelItem.find(".panel-body").append($(checkboxDiv));
                            panelGroupFeature.append(panelItem);
                            count++;
                        }
                    }
                    /**
                     * to handle checkboxs inside
                     * ~~~ dump step with [Component[items]]
                     * Step id is "panelFeatureGroup"
                     * inside this one, we just care about "checkbox"
                     */
                    console.log(dumpStepItemsId);
                    var checkboxStep = new Step("checkboxStep", step5ItemsId.item.item.panelGroupFeature, dumpStepItemsId);
                    checkboxStep.init();
                    /**
                     * once again, loop to render view for each checkboxDiv
                     */
//                    count = 0;
                    for(var i in features){
                        if(features.hasOwnProperty(i)){
                            var checkboxs = features[i];
                            var checkboxItem = checkboxStep.getItem(dumpStepItemsId.item.itemCheckbox[i]);
//                            console.log(dumpStepItemsId.item.itemCheckbox[i]);
//                            console.log(checkboxItem);
                            checkboxItem.render(checkboxs);
//                            count++;

                        }
                    }
                    panelGroupFeature.checkboxStep = checkboxStep;
                };
            };
            panelGroupFeature.render();
            panelGroupFeature.getData = function(){
                var r = {};
                r[this.name] = this.checkboxStep.getData();
                return r;
            };
            panelGroupFeature.setData = function(){};
            step5.bindEventHanlder = function(){
                var btnSubmit = step5.component.find("#" + step5ItemsId.event.btnSubmit);
                btnSubmit.on("click", function(){
                    console.log("btnSubmitStep5 click");
                    console.log("step5Data", step5.getData());
                    $("a[aria-controls='step-6']").click();
                    //call on step5
                });
            };
            step5.bindEventHanlder();
        });
    })(jQuery);
</script>