<h1>illuminate database</h1>
<?php //var_dump($this->postFeature["id"]); ?>
<?php //var_dump($this->postFeature["name"]); ?>
<?php //var_dump($this->postFeature["description"]); ?>
<?php var_dump($this->postFeature); ?>
<?php var_dump($this->postFeatureDetail); ?>
<?php var_dump($this->postFeatureDetail->getAttributes()); ?>
<?php var_dump($this->postFeatureDetail->getRelations()); ?>
<?php var_dump($this->postFeatureDetail->feature->getAttributes()); ?>
