<h1>create post</h1>
<form method="POST" action="" class="form-group">
    <label>name
        <input type="text" name="name" value="" class="form-control">
    </label>
    <label>description
        <input type="text" name="description" value="" class="form-control">
    </label>
    <label>menu order
        <input type="text" name="menu_order" value="" class="form-control">
    </label>
    <label>parent
        <input type="text" name="parent" value="" class="form-control">
    </label>
    <label>status
        <input type="text" name="status" value="" class="form-control">
    </label>
    <input type="submit" name="action" value="create" class="btn btn-default">
<!--    <button>create</button>-->
</form>