<h1>deep feature edit</h1>
<form>
    <input type="hidden" name="id" value="<?php echo $this->feature["id"]; ?>">
    <input type="submit" name="action" value="delete" class="btn btn-danger">
</form>
    <table class="table">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>menu_order</th>
            <th>parent</th>
            <th>status</th>
            <th>action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->children as $postFeature){ ?>
            <tr>
                <td><?php echo $postFeature["id"];?></td>
                <td><?php echo $postFeature["name"];?></td>
                <td><?php echo $postFeature["description"];?></td>
                <td><?php echo $postFeature["menu_order"];?></td>
                <td><?php echo $postFeature["parent"];?></td>
                <td><?php echo $postFeature["status"];?></td>
                <td>
                    <a href="/backend/post-feature/<?php echo $postFeature["id"];?>" class="btn btn-default">view</a>
                    <a href="/backend/post-feature/<?php echo $postFeature["id"];?>/edit" class="btn btn-default">edit</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>
