<div class="container">
    <h2>post feature</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <?php use Zend\View\Renderer\PhpRenderer;

    if(isset($this->msgCtrl)){
        echo $this->msgCtrl;
    } ?>
    <form method="GET" action="/backend/post-feature/create">
        <input type="submit" name="" value="create new one" class="btn btn-default">
    </form>
    <table class="table">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>menu_order</th>
            <th>parent</th>
            <th>status</th>
            <th>action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->paginator as $item){ ?>
            <tr>
                <td><?php echo $item["id"]; ?></td>
                <td><?php echo $item["name"]; ?></td>
                <td><?php echo $item["description"]; ?></td>
                <td><?php echo $item["menu_order"]; ?></td>
                <td><?php echo $item["parent"]; ?></td>
                <td><?php echo $item["status"]; ?></td>
                <td>
                    <a href="/backend/post-feature/<?php echo $item["id"]; ?>/edit"
                       class="btn btn-default">edit</a>
                    <a href="/backend/post-feature/<?php echo $item["id"]; ?>/delete" class="btn btn-default">delete</a>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <?php
    /** @var PHPRenderer $this */
    echo $this->paginationControl($this->paginator, 'Sliding', 'post-feature-paginator',
        array('route' => 'post-feature-paginator')); ?>
</div>
