<div class="container">
    <h2>post feature</h2>
    <p>The .table class adds basic styling (light padding and only horizontal dividers) to a table:</p>
    <?php if(isset($this->msg)){
        var_dump($this->msg);
    } ?>
    <form method="GET" action="/backend/post-feature/create">
        <input type="submit" name="" value="create new one" class="btn btn-default">
    </form>
    <table class="table">
        <thead>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>description</th>
            <th>menu_order</th>
            <th>parent</th>
            <th>status</th>
            <th>action</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->postFeatures as $postFeature){ ?>
        <tr>
            <td><?php echo $postFeature["id"];?></td>
            <td><?php echo $postFeature["name"];?></td>
            <td><?php echo $postFeature["description"];?></td>
            <td><?php echo $postFeature["menu_order"];?></td>
            <td><?php echo $postFeature["parent"];?></td>
            <td><?php echo $postFeature["status"];?></td>
            <td>
                <a href="/backend/post-feature/<?php echo $postFeature["id"];?>/edit" class="btn btn-default">edit</a>
                <a href="/backend/post-feature/<?php echo $postFeature["id"];?>/delete" class="btn btn-default">delete</a>
            </td>
        </tr>
        <?php } ?>
        </tbody>
    </table>
</div>
