<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>Thêm thành phố</h3>
            <form role="form" class="form-horizontal" method="post" name='formAdmin'>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="number-address">Tên thành phố: </label>
                        <input type="text" class="form-control" name="namecity"  id="namecity">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary btn-next">Add</button>
                    </div>
                    <div class="col-md-4">
                        <button type="reset" class="btn btn-primary" value="Reset">reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>