<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>danh sach tinhr thanh</h3>
            <?php
            if (count($this->flash)) {
                echo "<div class='alert alert-success'>";
                foreach ($this->flash as $mess) {
                    echo $mess;
                }
                echo "<div>";
            }
            ?>

            <table class="table table-striped">
                <tr>
                    <td>STT</td>
                    <td>ID</td>
                    <td>Tên tỉnh thành</td>
                    <td>Edit</td>
                    <td>Del</td>
                </tr>
                <?php
                if($data){
                    foreach ($data as $key=>$item) {
                       
                ?>
                <tr>
                    <td><?= $key+1 ?></td>
                    <td><?= $item['id'] ?></td>
                    <td><?= $item['name'] ?></td>
                    <td>
                       
                    </td>
                    <td><a href = '<?= $this->url('backend/district',array('action'=>'edit','id'=>$item['id'])) ?>'>Edit</td>
                    <td><a href = '<?= $this->url('backend/district',array('action'=>'del','id'=>$item['id'])) ?>' onClick="return confirm('Bạn thực sự muốn xóa');">Del</td>
                </tr>
                <?php
                     }
                }
                ?>
            </table>
        <div class="col-md-12">
            <a class="a-btn-submit" href="<?php echo $this->url('backend/district', array('action' => 'add')); ?>">ADD NEW</a>
        </div>
        </div>
    </div>
</div>
<?php 
//    echo $this->paginationControl($this->data, 'Sliding', 'test_pages', array("route" => "pager")); 
?>


