<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>danh sach tinhr thanh</h3>
            <?php
            if (count($this->flash)) {
                echo "<div class='alert alert-success'>";
                foreach ($this->flash as $mess) {
                    echo $mess;
                }
                echo "<div>";
            }
            ?>

            <table class="table table-striped">
                <tr>
                    <td>STT</td>
                    <td>ID</td>
                    <td>Tên tỉnh thành</td>
                    <td>Edit</td>
                    <td>Del</td>
                </tr>
                <?php
                if($data){
                    foreach ($data as $key=>$item) {
                ?>
                <tr>
                    <td><?= $key+1 ?></td>
                    <td><?= $item['id'] ?></td>
                    <td><?= $item['name'] ?></td>
                    <td><a href = '<?= $this->url('backend/province',array('action'=>'edit','id'=>$item['id'])) ?>'>Edit</td>
                    <td><a href = '<?= $this->url('backend/province',array('action'=>'del','id'=>$item['id'])) ?>'>Del</td>
                </tr>
                <?php
                     }
                }
                ?>
            </table>
            <div class="col-md-12">
                <form action="">
                    <div class="input-group">
                        <button type="submit" class="btn btn-primary btn-next">Add Category</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>