<div class="container">
    <div class="row">
        <div class="col-md-8">
            <h3>danh sach quận huyện</h3>
            <?php
            if (count($this->flash)) {
                echo "<div class='alert alert-success'>";
                foreach ($this->flash as $mess) {
                    echo $mess;
                }
                echo "<div>";
            }
            ?>

            <table class="table table-striped">
                <tr>
                    <td>STT</td>
                    <td>ID</td>
                    <td>Tên Phường/Xã</td>
                    <td>Phường/Xã</td>
                    <td>Edit</td>
                    <td>Del</td>
                </tr>
                <?php
                if($data){
                    foreach ($data as $key=>$item) {
//                        echo "<pre>";
//                        print_r($data);
                ?>
                <tr>
                    <td><?= $key+1 ?></td>
                    <td><?= $item['id'] ?></td>
                    <td><?= $item['name'] ?></td>
                    <td><?= $item['type'] ?></td>
                    <td><a href = '<?= $this->url('backend/ward',array('action'=>'edit','id'=>$item['id'])) ?>'>Edit</td>
                    <td><a href = '<?= $this->url('backend/ward',array('action'=>'del','id'=>$item['id'])) ?>' onClick="return confirm('Bạn thực sự muốn xóa');">Del</td>
                </tr>
                <?php
                     }
                }
                ?>
            </table>
        <div class="col-md-12">
          <form action="<?php echo $this->url('backend/ward', array('action' => 'add')) ?>">
            <div class="input-group">
              <button type="submit" class="btn btn-primary btn-next">Add Category</button>
            </div>
          </form>
        </div>
        </div>
    </div>
</div>
