<h3><?php echo $this->controller; ?></h3>
<div class="row">
    <div class="col-md-4 col-md-offset-4">
        <h3>Sign Up</h3>
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <a class="btn btn-block btn-social btn-facebook"><span
                        class="fa fa-facebook"></span>Facebook</a>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <a class="btn btn-block btn-social btn-google"><span
                        class="fa fa-google"></span>Google+</a>
            </div>
        </div>
        <div class="login-or">
            <hr class="hr-or">
            <span class="span-or">or</span>
        </div>
        <?php $loginForm = $this->loginForm;
        $loginForm->prepare();
        echo $this->form()->openTag($loginForm);; ?>
        <div class="form-group">
            <label>Username or email</label>
            <div><?php echo $this->formElement($loginForm->get('email')); ?>
                <span
                    class="common-error-msg"><?php echo $this->formElementErrors($loginForm->get('email')); ?></span>
            </div>
        </div>
        <div class="form-group">
            <label>Password</label>
            <div><?php echo $this->formElement($loginForm->get('password')); ?>
                <span
                    class="common-error-msg"><?php echo $this->formElementErrors($loginForm->get('password')); ?></span>
            </div>
        </div>
        <div><?php
            echo $this->formRow($loginForm->get('loginCsrf'));
            echo $this->formElement($loginForm->get('submit'));
            ?>
        </div>
        <?php echo $this->form()->closeTag($loginForm); ?>
    </div>
</div>
