    <div class="row">
        <div class="col-md-12">
            <h3>Thêm Trạng Thái</h3> 
            <?php if(isset($this->arrayParam['error']) == true) {?>
            <div class="alert alert-success">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 <?php foreach ($this->arrayParam['error'] as $key => $value){?>
	      	<p> <?php echo $value;?></p>
	      <?php }?>
            </div>
            <?php } ?>
            <form role="form" action="" class="form-horizontal" method="post" name='formAdmin'>
                <div class="col-md-12">
                    <div class="form-group">
                        <label for="number-address">Thêm trạng thái: </label>
                        <input type="text" class="form-control" name="namestatus"  value="<?php if(isset($this->arrayParam['post']['name'])==true) echo $this->arrayParam['post']['name']; ?>" id="namestatus">
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="col-md-2">
                        <button type="submit" class="btn btn-primary btn-next">Add</button>
                    </div>
                    <div class="col-md-4">
                        <button type="reset" class="btn btn-primary" value="Reset">reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>