<?php echo $this->doctype(); ?>
<html>
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle("web application"); ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <!-- Scripts -->
    <script type="application/javascript" src="https://code.jquery.com/jquery-2.2.3.min.js"></script>
    <script type="application/javascript"
            src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script type="application/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.10.0/js/bootstrap-select.min.js"></script>


    <link rel="stylesheet" href="/css/main.css">
    <script type="application/javascript" src=""></script>
</head>
<body>
<div class="container">
    <header>
        <h1>Backend</h1>
    </header>
    <hr>
    <?php echo $this->msgUtil; ?>
    <?php echo $this->content; ?>
    <hr>
    <footer>
        <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies
            Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
    </footer>
</div>

<?php echo $this->inlineScript() ?>
</body>
</html>
